### ISSUE TITLE
Configuration options for Kafka/RabbitMQ reconnect

### ISSUE THREAD

**Issue by mark--** [spring-cloud/spring-cloud-stream#541] opened 2016-05-17 12:15 UTC
The reconnect to Kafka works fine, but it is attempted with 'full speed' (about 10 per second on my machine). This behaviour should be configurable (for all binders). At least there should be a parameter for the intervall between two attempts and maybe some sort of backoff makes sense, too.

Furthermore, in the case of connection loss, an exception is logged. This should be replaced by dedicated logging.

**Comment by mbogoevici** [comment] 2016-05-17 13:57
Thanks Mark,

Both these issues would need to be fixed via Spring Integration Kafka, and we will address them as part of upgrading to SI Kafka 2.0 (which should be fairly soon).

**Comment by mbogoevici** [comment] 2016-05-31 16:50
@mark-- 

The reconnect frequency of the Kafka consumers to the brokers is set to 5 seconds, but I believe that the noise that you are currently seeing is caused by the Zookeeper client trying to reconnect. Are you stopping your Zookeeper ensemble as well ?

In the case of Zookeeper, the wait times on reconnect are random (between 0 and 1000ms) and I think that's what you see in the logs. Since that's just indicating that the client is trying to reconnect, I would suggest raising the logging levels to `ERROR` instead of `WARN`. We will set that by default in the client to avoid the noise.

**Comment by mbogoevici** [comment] 2016-06-01 18:40
Closed via #556 in https://github.com/spring-cloud/spring-cloud-stream/commit/6c4a271078bd8e32ed3e88ebad2c08755a39bbbe and cherry-picked to 1.0.x branch.

**Closed by mbogoevici** 2016-06-01 18:40 UTC
Labels: in pr
