### ISSUE TITLE
Can't create CRaC checkpoint, fails with the error message "CheckpointOpenSocketException: Socket[addr=rabbitmq..."

### ISSUE THREAD

**Issue by magnus-larsson** [spring-cloud/spring-cloud-stream#3060] opened 2024-12-29 22:11 UTC
`spring-cloud-stream` seems to prevent creating CRaC checkpoints. 

**The issue**
CraC checkpoints fail with errors that indicate that connections to the message broker, e.g., RabbitMQ or Kafka, are not closed by Spring Cloud Stream before the checkpoint.

**How to reproduce**

1. Get the source code, add a Docker Compose file for RabbitMQ and start RabbitMQ:

       git clone https://github.com/spring-guides/gs-spring-cloud-stream.git
       cd gs-spring-cloud-stream

2. Add a Docker Compose file for RabbitMQ and start RabbitMQ:

       cat <<EOF > docker-compose.yml
       services:
         rabbitmq:
           image: rabbitmq:3.11.8-management
           ports:
             - 5672:5672
             - 15672:15672
       EOF

       docker compose up -d

3. Build and start the sink app in a Docker container

       cd name-sink
       ./mvnw package

       docker run -it --rm --network gs-spring-cloud-stream_default -v ${PWD}:/demo --privileged --name demo azul/zulu-openjdk:21-jdk-crac bash

       # Commands to be executed in the container
       cd demo

       export SPRING_RABBITMQ_HOST=rabbitmq
       java -XX:CRaCCheckpointTo=checkpoint -jar target/name-sink-0.0.1-SNAPSHOT.jar

4. Verify a successful connection to RabbitMQ by looking for log output similar to:

       2024-12-29T21:41:36.224Z  INFO 199 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#61ff6a49:0/SimpleConnection@41f964f9 [delegate=amqp://guest@172.18.0.2:5672/, localPort=47752]

5. In a second terminal, try taking a checkpoint of the sink app in the Docker container:

       docker exec demo jcmd target/name-sink-0.0.1-SNAPSHOT.jar JDK.checkpoint

   The checkpoint command will be aborted with error messages like the following:

       An exception during a checkpoint operation:
       jdk.internal.crac.mirror.CheckpointException
                Suppressed: java.nio.channels.IllegalSelectorException
                        at java.base/sun.nio.ch.EPollSelectorImpl.beforeCheckpoint(EPollSelectorImpl.java:401)
                        at java.base/jdk.internal.crac.mirror.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:43)
                        ...
                Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: sun.nio.ch.ServerSocketChannelImpl[/[0:0:0:0:0:0:0:0]:46359]
                        at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:68)
                        ...
                Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: Socket[addr=rabbitmq/172.18.0.2,port=5672,localport=54484]
                        at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:68)
                        ...

   The error messages indicate that the checkpoint was aborted since the connection with RabbitMQ was not closed before the checkpoint.

**Version of the framework**
Java 21
Spring Boot 3.3.1
Spring Cloud 2023.0.2

**Expected behavior**
That the checkpoint command runs successfully.

**Additional context**
The same issue can be reproduced using the Kafka binder.
Using Spring-Kafka without Spring Cloud Stream works fine with CRaC.

**Comment by artembilan** [comment] 2024-12-30 17:19
Thank you for such a great instruction how to reproduce!
So, with this command:
```
root@6fb764a3c296:/demo# java -XX:CRaCCheckpointTo=checkpoint -XX:+UnlockDiagnosticVMOptions -XX:+CRaCPrintResourcesOnCheckpoint -Djdk.crac.collect-fd-stacktraces=true -jar target/name-sink-0.0.1-SNAPSHOT.jar
```
I was able to find the guilty place in the code:
```
An exception during a checkpoint operation:
jdk.internal.crac.mirror.CheckpointException
        Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenSocketException: Socket[addr=host.docker.internal/192.168.65.254,port=5672,localport=48490]
                at java.base/jdk.internal.crac.JDKSocketResourceBase.lambda$beforeCheckpoint$0(JDKSocketResourceBase.java:68)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:170)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:315)
                at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:328)
        Caused by: java.lang.Exception: This file descriptor was created by main at epoch:1735578997244 here
                at java.base/jdk.internal.crac.JDKFdResource.<init>(JDKFdResource.java:60)
                at java.base/jdk.internal.crac.JDKSocketResourceBase.<init>(JDKSocketResourceBase.java:44)
                at java.base/jdk.internal.crac.JDKSocketResource.<init>(JDKSocketResource.java:38)
                at java.base/java.net.SocketImpl$1.<init>(SocketImpl.java:78)
                at java.base/java.net.SocketImpl.<init>(SocketImpl.java:77)
                at java.base/sun.nio.ch.NioSocketImpl.<init>(NioSocketImpl.java:139)
                at java.base/java.net.SocketImpl.createPlatformSocketImpl(SocketImpl.java:54)
                at java.base/java.net.Socket.createImpl(Socket.java:583)
                at java.base/java.net.Socket.<init>(Socket.java:189)
                at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:261)
                at com.rabbitmq.client.impl.SocketFrameHandlerFactory.createSocket(SocketFrameHandlerFactory.java:77)
                at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:58)
                at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1249)
                at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1198)
                at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connectAddresses(AbstractConnectionFactory.java:668)
                at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connect(AbstractConnectionFactory.java:637)
                at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:584)
                at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:726)
                at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:257)
                at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2249)
                at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2222)
                at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2202)
                at org.springframework.amqp.rabbit.core.RabbitAdmin.declareExchange(RabbitAdmin.java:235)
                at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.customizeAndDeclare(RabbitExchangeQueueProvisioner.java:696)
                at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.declareExchange(RabbitExchangeQueueProvisioner.java:687)
                at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.doProvisionConsumerDestination(RabbitExchangeQueueProvisioner.java:257)
                at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionConsumerDestination(RabbitExchangeQueueProvisioner.java:196)
                at org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner.provisionConsumerDestination(RabbitExchangeQueueProvisioner.java:84)
                at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:524)
                at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:103)
                at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:144)
                at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:186)
                at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:139)
                at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:98)
                at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
                at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
                at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:59)
                at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:285)
                at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:469)
                at java.base/java.lang.Iterable.forEach(Iterable.java:75)
                at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:257)
                at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:202)
                at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
                at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
                at com.example.stream.namesink.NameSinkApplication.main(NameSinkApplication.java:10)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
                at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
                at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
```

Will look further what is going on and why.

**Comment by artembilan** [comment] 2024-12-30 18:04
OK. After adding:
```
		<dependency>
			<groupId>org.crac</groupId>
			<artifactId>crac</artifactId>
		</dependency>
```
into that `name-sink` POM it has started working as expected.

After enabling `--logging.level.org.springframework.context.support=debug` for that `java -XX:CRaCCheckpointTo=checkpoint -jar target/name-sink-0.0.1-SNAPSHOT.jar` I would expect something like:
```
logger.debug("Stopping Spring-managed lifecycle beans before JVM checkpoint");
```
from the `DefaultLifecycleProcessor.CracResourceAdapter`, when we call that `jcmd target/name-sink-0.0.1-SNAPSHOT.jar JDK.checkpoint`.
Since it is not there I realized that something is off with classpath.
So, decided to add that dependency into the project since it is mentioned in the docs: https://docs.spring.io/spring-framework/reference/integration/checkpoint-restore.html.
And now it works.

Yes, I had an expectations since `zulu-openjdk:21-jdk-crac` is in use, that `ClassUtils.isPresent("org.crac.Core", getClass().getClassLoader())` should be OK.
But apparently that is not and we have to add `crac` dependency explicitly to make it working.

Closing as `Works as Designed`.

**Closed by artembilan** 2024-12-30 18:04 UTC

**Comment by magnus-larsson** [comment] 2025-01-03 11:00
Hello, and thanks for looking into this issue!

Sorry for the mistake of not adding the CRaC dependency before validating if the issue still exists in this example.
I detected the problem in a more complex code base and tried to create a minimal example where the issue could be reproduced. 

I will create a new example that includes the CRaC dependency that can be used to reproduce the problem!

**Comment by magnus-larsson** [comment] 2025-01-03 11:12
Please see https://github.com/spring-cloud/spring-cloud-stream/issues/3062 for a better example of how to reproduce the issue; thanks!
