### ISSUE TITLE
Global contentType for all bindings

### ISSUE THREAD

**Issue by ab712** [spring-cloud/spring-cloud-stream#699] opened 2016-10-28 23:16 UTC
Is it possible to configure contentType for all bindings with just one property instead of per-binding?

Currently this would be necessary 10+ times in my config:
`spring.cloud.stream.bindings.output.contentType=application/json;charset=UTF-8`

**Comment by mbogoevici** [comment] 2016-10-28 23:29
Hi @ab712,

Thanks for the interest. There currently is an open issue for global/default settings. We hope to get to it in one of our coming releases.

https://github.com/spring-cloud/spring-cloud-stream/issues/446

**Comment by mbogoevici** [comment] 2016-12-01 20:36
Closing this as it is a duplicate of #446

**Closed by mbogoevici** 2016-12-01 20:36 UTC
