### ISSUE TITLE
Spring Cloud Stream - Kafka - Confluent Kafka - Failed to start bean 'inputBindingLifecycle'

### ISSUE THREAD

**Issue by fraballi** [spring-cloud/spring-cloud-stream#1763] opened 2019-07-15 20:48 UTC
Hi, I got an error using spring-cloud-stream (2.2.0.RELEASE).
I'm trying to subscribe and send stream messages. But i got that error: `org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode
`.
These are some logs:
`2019-07-15 16:38:35.491  INFO 23402 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.0`.

I used Confluent's latest dockerized Kafka/Zookeeper, with Kafka:
`2.2.1-cp1 (Commit:7ff42411baaba1ae)`

`confluentinc/cp-kafka             5.2.2                                 `
`confluentinc/cp-zookeeper         5.2.2`

Complete log:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-15 16:38:35.531 ERROR 23402 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.fraballi.connectors.iot.schema.SchemaRegistryServerApplication.main(SchemaRegistryServerApplication.java:21) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:715) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:499) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:615) ~[kafka-clients-2.0.0.jar:na]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:132) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:115) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createConsumer(DefaultKafkaConsumerFactory.java:101) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.kafka.core.ConsumerFactory.createConsumer(ConsumerFactory.java:66) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.kafka.core.ConsumerFactory.createConsumer(ConsumerFactory.java:53) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.kafka.core.ConsumerFactory.createConsumer(ConsumerFactory.java:42) ~[spring-kafka-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.lambda$getPartitionInfo$4(KafkaMessageChannelBinder.java:855) ~[spring-cloud-stream-binder-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.lambda$getPartitionsForTopic$2(KafkaTopicProvisioner.java:454) ~[spring-cloud-stream-binder-kafka-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:449) ~[spring-cloud-stream-binder-kafka-core-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.getPartitionInfo(KafkaMessageChannelBinder.java:852) ~[spring-cloud-stream-binder-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.processTopic(KafkaMessageChannelBinder.java:632) ~[spring-cloud-stream-binder-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:469) ~[spring-cloud-stream-binder-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:134) ~[spring-cloud-stream-binder-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:402) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:99) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:144) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:144) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:122) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:254) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:48) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.JsonNode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 49 common frames omitted
```

**Comment by olegz** [comment] 2019-07-16 15:32
The error is pretty clear. You are missing `org.codehaus.jackson.JsonNode` which means you are missing one of the [dependent JARs](https://mvnrepository.com/artifact/org.codehaus.jackson). Spring Cloud Stream does not use it so it must be something required by your custom code.
IN any event adding the correct dependency will alleviate this error.

**Comment by fraballi** [comment] 2019-07-16 16:58
I'm certain it should be, though, which spring-cloud-stream dependency wraps jackson-core? I referred to this Github link https://github.com/spring-cloud/spring-cloud-stream-binder-kafka, where it tells one can use both variants, I chose 'starter'. Shall I add any other "good-to-go" dependency? Also, I checked this: https://spring.io/projects/spring-kafka (compatibility table). Could you tell that I'm using the right combination?

**Comment by fraballi** [comment] 2019-07-16 19:27
Had to include:
```
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-asl</artifactId>
			<version>1.9.13</version>
		</dependency>
```
I searched on this dependency and it's very old in maven (2013 commit) and is recommended to have `https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind`, perhaps a suggestion for the Spring Team to change for the maintained one ;-).

**Comment by garyrussell** [comment] 2019-07-17 13:55
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile


Boot is the single source of truth (mostly); you should let it manage your versions, or you can manually look up the versions it pulls in [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml) (switch to the tag for your boot version).

I just created a new project (via start.spring.io) with Boot 2.1.6 and added databind and this is the pom...

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.6.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>scs1763</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>scs1763</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.SR2</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

and the boot managed versions...

```
[INFO] 
[INFO] ------------------------< com.example:scs1763 >-------------------------
[INFO] Building scs1763 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ scs1763 ---
[INFO] com.example:scs1763:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.cloud:spring-cloud-stream:jar:2.1.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.21:compile
[INFO] |  |  \- org.hibernate.validator:hibernate-validator:jar:6.0.17.Final:compile
[INFO] |  |     +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.springframework:spring-messaging:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.1.8.RELEASE:compile
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.2.10.RELEASE:compile
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:5.1.6.RELEASE:compile
[INFO] |  +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
[INFO] |  |     \- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  +- org.springframework.integration:spring-integration-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  +- org.springframework.retry:spring-retry:jar:1.2.4.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-function-context:jar:2.0.2.RELEASE:compile
[INFO] |     \- org.springframework.cloud:spring-cloud-function-core:jar:2.0.2.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:2.1.3.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-stream-binder-kafka-core:jar:2.1.3.RELEASE:compile
[INFO] |  |  \- org.springframework.integration:spring-integration-kafka:jar:3.1.0.RELEASE:compile
[INFO] |  \- org.apache.kafka:kafka-clients:jar:2.0.1:compile
[INFO] |     +- org.lz4:lz4-java:jar:1.4.1:compile
[INFO] |     +- org.xerial.snappy:snappy-java:jar:1.1.7.1:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO] +- org.springframework.kafka:spring-kafka:jar:2.2.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.1.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-tx:jar:5.1.8.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.1.6.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.6.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.1.6.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.6.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.3:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.2:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.4:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.assertj:assertj-core:jar:3.11.1:test
[INFO] |  +- org.mockito:mockito-core:jar:2.23.4:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.9.13:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.13:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:5.1.8.RELEASE:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.6.2:test
[INFO] +- org.springframework.cloud:spring-cloud-stream-test-support:jar:2.1.3.RELEASE:test
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.6.RELEASE:compile
[INFO] +- org.springframework.kafka:spring-kafka-test:jar:2.2.7.RELEASE:test
[INFO] |  +- org.apache.kafka:kafka-clients:jar:test:2.0.1:test
[INFO] |  +- org.apache.kafka:kafka_2.11:jar:2.0.1:test
[INFO] |  |  +- net.sf.jopt-simple:jopt-simple:jar:5.0.4:test
[INFO] |  |  +- com.yammer.metrics:metrics-core:jar:2.2.0:test
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.11.12:test
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.12:test
[INFO] |  |  +- com.typesafe.scala-logging:scala-logging_2.11:jar:3.9.0:test
[INFO] |  |  +- com.101tec:zkclient:jar:0.10:test
[INFO] |  |  \- org.apache.zookeeper:zookeeper:jar:3.4.13:test
[INFO] |  |     \- org.apache.yetus:audience-annotations:jar:0.5.0:test
[INFO] |  \- org.apache.kafka:kafka_2.11:jar:test:2.0.1:test
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.559 s
[INFO] Finished at: 2019-07-17T09:52:28-04:00
[INFO] ------------------------------------------------------------------------
```

It makes your life much easier if you use Boot's dependency management.

**Comment by fraballi** [comment] 2019-07-17 14:38
Thanks a lot for the confirmation! 
:+1: 
I checked that **pom.xml** on Github demos (2.1.6.RELEASE version). Would be nice updating those examples with latest (2.2.7) as you kindly mentioned, but also spring-cloud docs, that explains for 'starter' (contains '-binder') . Also, adding 'jackson' does not fit on 2.2.0.RELEASE. because uses an old version from 'codehaus' (weird, though). 

These were the links consulted:
- [Spring-Cloud-Stream-Kafka](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_usage)
- [Spring-Kafka-Integration](https://docs.spring.io/spring-kafka/docs/current/reference/html/#si-kafka)

I think could be a confusion on available options, whether: (_spring-cloud-stream_ or _spring-integration_). ;-)

Still, great stack guys :100:

**Comment by garyrussell** [comment] 2019-07-17 15:53
```
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:715) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:469) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:499) ~[kafka-clients-2.0.0.jar:na]
...
```

That is caused by your configuration - kafka is trying to load a class that you have specified somewhere in your `ConsumerConfig`.

**Comment by garyrussell** [comment] 2019-07-17 16:00
The only properties of type `CLASS` in Consumer config are

```java
                                .define(KEY_DESERIALIZER_CLASS_CONFIG,
                                        Type.CLASS,
                                        Importance.HIGH,
                                        KEY_DESERIALIZER_CLASS_DOC)
                                .define(VALUE_DESERIALIZER_CLASS_CONFIG,
                                        Type.CLASS,
                                        Importance.HIGH,
                                        VALUE_DESERIALIZER_CLASS_DOC)
```

So it's odd that you have `JsonNode` there.

**Comment by fraballi** [comment] 2019-07-17 17:07
It makes sense, though, I don't use manual configuration (like pure Spring-Kafka beans approach) besides: `application.yml`.
I don't have a ConsumerConfig declared, using only spring streaming features from spring auto-configuration during initialization. So I presume, it is during SnakeYML or something else recurring to Jackson (JsonNode) auto-configuration. Herewith, my file:

```
server:
  port: 8990
spring:
  application:
    name: schema-registry-service
  cloud:
    stream:
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url:  http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
          brokers:
          - localhost:29092
      bindings:
        input:
          group: test-stream-group
          destination: test
          content-type: application/*+avro
        output:
          destination: test
          content-type: application/*+avro
```

:+1:

**Comment by garyrussell** [comment] 2019-07-17 18:31
Strange.

```
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
```

These end up in `ConsumerConfig` created from the boot properties, in the consumer constructor. I have no idea where `JsonNode` is coming from.

If you have a small app that reproduces the problem, I can take a look.

**Comment by fraballi** [comment] 2019-07-17 19:48
Superb! Those could be the annoying properties we looked for. No worries mate, I fixed it including that old dependency. I'm certain that should work changing the version with your previous **pom.xml**. It's just that I'm using Confluent Schema Registry, spring docs talk on Confluent Serializer/Deserializer use case. Perhaps, I should create my own combo, but as long as it works...DRY principles applied! :+1:

**Comment by garyrussell** [comment] 2019-07-18 09:02
Bingo.

https://github.com/confluentinc/schema-registry/blob/c6eff7096ceaf5cc4d2d7a883f93d620b1bd2d66/avro-converter/src/main/java/io/confluent/connect/avro/AvroData.java#L40-L45

I can't believe they are still using Jackson 1.

**Comment by fraballi** [comment] 2019-07-18 11:20
Funny things happens when a repo speaks by himself. Beautiful @garyrussell!

**Comment by olegz** [comment] 2019-07-25 15:33
Seems like this issue has been resolved, so I am closing it. Please feel free to reopen or raise the new one if there are more questions.

**Closed by olegz** 2019-07-25 15:33 UTC
Labels: waiting-on-feedback
