### ISSUE TITLE
Partitioning and Multi-Threaded processing of Queue Messages - Messages Not Being Delivered

### ISSUE THREAD

**Issue by ulmermark** [spring-cloud/spring-cloud-stream#663] opened 2016-09-21 19:29 UTC
Help me if I am doing something wrong here.

My desire is to use partitioning/concurrency to insure thread-affinity as well as increase throughput of the application.

Spring Boot 1.4.0.RELEASE
Spring Cloud Starter Stream Rabbit - 1.0.0.RELEASE

I have an app that is queuing messages to a Processor.OUTPUT and consuming on Process.INPUT and when I have no partitioning I see all messages queued and consumed ( 8 for 8 in thiscase)

I introduce partitioning using the following:

```
  stream:
    bindings:
      input:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        consumer:
           concurrency: 1
           partitioned: true

      output:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        producer:
           partitioned: true
           partitionCount: 1
           partitionKeyExpression: payload.biller.externalKey
```

And receive 8 for 8 messages queue and consumed as shown in attached file.

[1-partitioned-logs.txt](https://github.com/spring-cloud/spring-cloud-stream/files/485856/1-partitioned-logs.txt)

If I change the concurrency to 2 and the partitionCount to 2, I do not get all 8 messages consumed as shown in the attached log file:

```
  stream:
    bindings:
      input:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        consumer:
           concurrency: 2
           partitioned: true

      output:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        producer:
           partitioned: true
           partitionCount: 2
           partitionKeyExpression: payload.biller.externalKey
```

[2-partitioned-logs.txt](https://github.com/spring-cloud/spring-cloud-stream/files/485873/2-partitioned-logs.txt)

**Comment by ulmermark** [comment] 2016-09-21 19:52
Ill add one other peculiarity...If I remove partitioning / concurrency and restart the application.  The original 8 messages are reprocessed without ever "re-queuing" the messages.

[3-no-partitioning-restart.txt](https://github.com/spring-cloud/spring-cloud-stream/files/485918/3-no-partitioning-restart.txt)

**Comment by garyrussell** [comment] 2016-09-21 19:52
First, it's a bit odd for an app to send messages to itself.

Second, when you have a partitioned consumer, you need an `instance-index1` property.

    spring.cloud.stream.instance-index=1

You need two instances of the consumer one for index 0 (default) and one for index 1.

You are only getting the messages for index 0.

**Comment by mbogoevici** [comment] 2016-09-21 20:07
"Ill add one other peculiarity...If I remove partitioning / concurrency and restart the application. The original 8 messages are reprocessed without ever "re-queuing" the messages." 

It's hard to tell what's going on there without taking a look at what the application does - how messages are sent, etc. If you can provide an example that reproduces this, it would be helpful. Configuration alone doesn't say much. Thanks.

**Comment by mbogoevici** [comment] 2016-11-16 15:14
Hi @ulmermark - I will close this since it hasn't been active for a while - if you have any update, please feel free to reopen and add more details.

**Closed by mbogoevici** 2016-11-16 15:14 UTC
