### ISSUE TITLE
Spring Cloud Stream duplicates on instance reboot

### ISSUE THREAD

**Issue by DenisTunin** [spring-cloud/spring-cloud-stream#1683] opened 2019-04-05 15:31 UTC
Used the kafka stream implementation, by default `max.poll.records = 500` and if you interrupt in the middle, half will be duplicated. 
Not reproduced in debug mode.

**Comment by olegz** [comment] 2019-04-05 16:06
I am going to close this issue since there are no ways for us to reproduce it  - there is no explanation or a sample app or even instructions on what needs to be done so we can observe, reproduce, diagnose and fix the issue.

Also there are no details on your configuration yet you are saying that it can not be reproduced in debug mode which often is a symptom of user missconfiguration. 

So, please consider giving it some thought and providing enough details so we can act on it.

**Closed by olegz** 2019-04-05 16:06 UTC
