### ISSUE TITLE
Allow multiple Dynamic consumers for the same binding target in a single JVM

### ISSUE THREAD

**Issue by satishkumars** [spring-cloud/spring-cloud-stream#1155] opened 2017-12-11 15:05 UTC
Is there a possibility to have more that one dynamic consumer for the same binding target. ??

Our application is creating consumers dynamically using "bindingService". 

`SubscribableChannel newChannel = (SubscribableChannel) bindingTargetFactory.createInput(inputName);
Collection<Binding<SubscribableChannel>> bindings = bindingService.bindConsumer(newChannel, consumerName);`

Its not possible to register more than one dynamic consumer with the same 'bindingTarget'. The registerErrorInfrastructure() method throws error for as there already exists a bean with the same name.

`Caused by: java.lang.IllegalStateException: Could not register object [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer@2484bb4b] under bean name 'output.test.errors.recoverer': there is already object [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer@4a76c693] bound
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:130) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:936) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:379) ~[spring-cloud-stream-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:402) ~[spring-cloud-stream-binder-rabbit-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:98) ~[spring-cloud-stream-binder-rabbit-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:233) ~[spring-cloud-stream-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	... 16 common frames omitted`

are there other ways to handle this ??
we would like to have multiple consumers for the same 'bindingTarget'.

**Comment by satishkumars** [comment] 2017-12-11 16:43
Thanks for accepting the make improvements.

**Comment by olegz** [comment] 2018-01-11 18:52
@satishkumars I've just tested it with current master and had no issues, but also noticed that you are using 1.3. So my question is; Could you switch to 2.0 snapshots or 1.3 is a requirement for you?

**Comment by olegz** [comment] 2018-01-11 19:03
I can't seem to reproduce it in 1.3 either. Here is my sample code.
```
BindingTargetFactory bindingTargetFactory = context.getBean(BindingTargetFactory.class);
BindingService bindingService = context.getBean(BindingService.class);
SubscribableChannel newChannel = (SubscribableChannel) bindingTargetFactory.createInput("myChannel"); 
Collection<Binding<SubscribableChannel>> bindings = bindingService.bindConsumer(newChannel, "consumerA");
bindings = bindingService.bindConsumer(newChannel, "consumerB");
```

Also, 1.3.0.RELEASE is also somewhat outdated. Could you please switch to s-c-stream version `Ditmars.SR3` which will pull `spring-cloud-stream-binder-rabbit-1.3.3.RELEASE.jar`

**Comment by olegz** [comment] 2018-01-11 19:25
Actually was able to reproduce it with this code
```
Collection<Binding<SubscribableChannel>> bindings = bindingService.bindConsumer(newChannel, "consumerA");
bindings = bindingService.bindConsumer(newChannel, "consumerA");
```
But now wondering why would you want to register second consumer under the same name?
Could you please explain what is it you are trying to accomplish? Perhaps we can suggest a better way, since as of now I don't believe there is anything that needs fixing.

**Comment by olegz** [comment] 2018-01-16 01:58
It appears there is no issue and the exception is thrown due to the naming conflict where instance of the consumer with the same name has already been registered.
Closing it.

**Closed by olegz** 2018-01-16 01:58 UTC
Labels: binding-improvements

**Comment by satishkumars** [comment] 2018-01-16 11:26
Agree this not a bug, can this added as an improvement.
@olegz 
the idea is to have multiple consumers to the same channel within the JVM.
usage scenario :
using cloud stream connected to web-sockets that stream messages to browser clients...
we want to have multiple browser clients can be connected to the same target queue

**Comment by olegz** [comment] 2018-01-16 12:40
As I pointed out earlier. You CAN do exactly what you want. 
Your issue is you were trying to register them under the same name and that will not work and should not work. However if you do it with different name (e.g., attaching some instance if suffix - 'consumer-1', 'consumer-2' etc), then you should have no issues (see below).
```
bindingService.bindConsumer(targetChannel, "consumer-A");
bindingService.bindConsumer(targetChannel, "consumer-B");
bindingService.bindConsumer(targetChannel, "consumer-C");
````
