### ISSUE TITLE
If consumer and producer agree on the content type of a message coercion should be automatic

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#156] opened 2015-10-19 18:37 UTC
If a consumer and producer *don't* specify a content type (via `spring.cloud.stream.bindings.*.contentType`) then as long as they share a class definition for the payload (a domain object) then the message will flow. That's uncomfortable for 2 reasons: first it forces  them to share the domain class (or have an identical class with the same FQCN), and second it uses a default content type which is not interopable (Java serialization basically, not JSON or protobuf or whatever).

As soon as you specify the content type (e.g. as `application/json` for interop / human readable messages), the system breaks because JSON gets converted to a String and the receiver can't process it as a domain object any more (he has to manually convert the String to a domain object, going through 2 layers of conversion, from String to JSON to Object).

I propose that if the consumer and producer agree on the content type (e.g. `application/json`) then Spring Cloud Stream (or Spring Integration) should be able to handle the conversion and type coercion.

Marius has pointed out that you have a similar situation in REST endpoints where the solution is `HttpMessageConverters` that are mime-type as well as Java type aware. The payload is essentially bytes (or Strings) as far as the "dumb pipes" model is concerned (Spring Cloud Stream), but it carries content type headers, a bit like an HTTP request.

**Comment by markfisher** [comment] 2015-10-20 12:43
+1 for interop out of the box and *not* promoting shared classes (if supported at all, that should at least not be the simplest thing to do)

**Comment by markfisher** [comment] 2015-10-20 12:45
If a consumer does expect a JSON String, then a `Converter` with target type `String` should be registered for the `application/json` MIME type.

**Comment by mbogoevici** [comment] 2015-10-20 12:54
The problem is the other way around - the incoming data is `String` and it needs conversion to `Vote` in the downstream handler method. One way to solve it is to add `contentType=application/x-java-object;type=demo.Vote` but that feels a bit iffy. I guess we could register a `Converter<String,Object>` that assumes JSON, but then again, that feels a bit too opinionated without further consideration (it would assume that any String is JSON, which is maybe ok, if it wasn't for XML). So perhaps a solution that combines OOTB SI conversion with the presence of the original type (`application/json`) in the message header would be an option. Or perhaps we could have something like `@EnableJsonConversion`. I think that we need to explore the option space and try to figure out what's best there.

**Comment by markfisher** [comment] 2015-10-20 13:47
Not saying this is how `spring-cloud-stream` works currently but how it should - to see if we're on the same page... Let's just take the actual `String` as inbound payload case with 3 examples: JSON text, XML text, or plain ole text. Those inbound messages should carry contentType headers with MIME types `application/json`, `application/xml` (or `text/xml`), and `text/plain` respectively. The consumer binding properties may explicitly provide a target type, but if not, standard SI conversion should apply when the method-to-be-invoked has been determined. Does that make sense?

**Comment by ericbottard** [comment] 2015-10-20 14:15
> Those inbound messages should carry contentType headers

What exactly do you mean? I think we're back to my point that this could work with adapters where the concept of mime type applies, but not for others.

i.e.
```
 http | log
^    ^
1    2
```

At point 1, there is intrinsic content type by virtue of the `Content-Type` http header, and at point 2, this could be overridden by `--outputType=xxx`

But for the following case, this falls short:
```
tcp | log
```

So, maybe we should allow (an equivalent) of `--inputType=xxx` for a __source__?

**Comment by ericbottard** [comment] 2015-10-20 14:23
Also, I think there is something we're missing when saying

> Let's just take the actual String as inbound payload case with 3 examples: JSON text, XML text, or plain ole text.

There is no `String` as payload. There are only "bytes". ie `[3c 3f 78 6d 6c 0a]` with `text/plain` could be seen as a `String`, but with `application/octet-stream` it's bytes, with `text/xml` it could be the start of an xml document, _etc._ My point being: when it's on the wire, it does not have a type _per se_. It is given a type by
1. an accompanying "content type"  header (e.g. the `Content-Type` http header, external)
2. a header s-c-s sets, which may or may not be understood by the middleware the message flows in

**Comment by markfisher** [comment] 2015-10-20 14:29
Yes, good points. We should be clear in the distinction between cases where the "other side" of the producer->consumer relationship is a `spring-cloud-stream` module vs. when it's not (e.g. http or tcp). In the former case, the actual bytes on the wire *might* be sourced from a `String` via UTF-8 encoding, and in that case those details should be reflected in the headers of the Message. However, as you point out, part of the clarification of the role for MIME types includes mapping to/from other protocols (something SI can handle, e.g. for HTTP or RabbitMQ) as well as accepting raw messages with no context.

**Comment by mbogoevici** [comment] 2015-10-20 15:15
I think that the context of this issue is strictly producer->consumer, where it seems that we could do the type conversion in the handler based on the original content type of the inbound message, because we have enough information carried around (original content type, that is). Currently that is not supported, because we do not act on it outside the binder. While building on top of SI's conversion support, this is the kind of OOTB configuration that SCS could provide. 

We could solve this problem by doing the coercion directly in the binder (by simply setting an appropriate `input.contentType`), but given the context above, it seems like we could do something cleverer.

Surely, we could apply the same concepts to other situations, where content type is available (like HTTP), and assume a default content type if no header is present (like FTP).

**Comment by markfisher** [comment] 2015-10-20 17:03
Then for modules such as FTP, the content type could be exposed as a configurable property (with a documented default)?

**Comment by mbogoevici** [comment] 2015-10-20 17:13
Sorry, I meant TCP not FTP, but yes.

**Comment by dsyer** [comment] 2016-01-21 17:59
Ping. Let's resurrect this one now that s-c-stream is nearing 1.0. I believe we need to do a better job here. Here's a summary of the current situation (correct me if I'm wrong):

On the producer I can put `spring.cloud.stream.bindings.output.content-type=application/json` and the message payload will be a JSON String (technically a byte array I know, but the conversion from a POJO to JSON is done by Spring and a header is attached to say what it did). This is good, and fine.

On the consumer, the JSON is not unpacked into an ojbect because there is no information in the headers to say what kind of object it is. This is good because we don't want brittleness and poor inerop caused by shared types on producer and consumer. So it's passed on downstream through the s-c-stream chain as a String (I don't know why it picks String, but that's the observation I made).

The message reaches a handler like this one:

```
@ServiceActivator(inputChannel = Sink.INPUT)
public void accept(Vote vote) {
...
}
```

So the application developer has bound the "input" channel to a strongly typed method. At this point the stars should align and something in Spring Cloud Stream should be able to figure out that the message can easily be converted to a `Vote` because it is plainly JSON (judging by the message headers), the target handler wants a POJO, and we have an `ObjectMapper` available.

Unfortunately, what happens is that the handler blows up saying 

```
...
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 8): Method call: Method accept(java.lang.String) cannot be found on demo.CounterApplication$$EnhancerBySpringCGLIB$$eaa35de6 type
	at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:211) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:125) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330) ~[spring-expression-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:166) ~[spring-integration-core-4.2.4.RELEASE.jar:na]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317) ~[spring-integration-core-4.2.4.RELEASE.jar:na]
...
```

You can fix it by declaring the content type differently to the default content type for the input channel:

```
spring.cloud.stream.bindings.intput.content-type=application/x-java-object;type=demo.Vote
```

This is mechanical (boiler plate) for the application developer. In an ideal world it should be possible to make this behaviour the default. It is also a little strange to put `application/json` in one end of the pipe and see it apparently come out as something completely different, viz `application-x-java-object`. So in the ideal world we would go a step further and make the declared content-type a conversion hint for data on the wire (so `application/json` on both sides would be redundant, but everything would work).

Do we have a proposal for a solution yet?

**Comment by dsyer** [comment] 2016-01-22 09:32
Even worse (if you ask me): if the user doesn't supply *any* content type on either side and there happens to be a class called `demo.Vote` on both sides, then everything will work, but only if the two classes have identical declarations. This out-of-the-box easy path serves to encourage the bad practice sharing classes between producer and consumer, and gives users a false sense of security in demo and getting started, plus it is terrible for interop because the payloads are transported as `Serializable` bytes by default.

**Comment by ilayaperumalg** [comment] 2016-01-22 09:56
In most cases, I think the problem is setting the `contentType` to `text/plain` instead of `application/json` for the JSON String during the serialization process at the producer. If the payload is of type **String** then the `contentType` is automatically set to use `text/plain`. I believe this problem can be fixed by setting the contentType that is set in the bindingProperties. This will make sure the expected contentType (`application/json` for example) is set when the deserialization process takes place at the consumer.

I am trying out some changes to propose an idea and will share it once ready.

**Comment by ilayaperumalg** [comment] 2016-01-22 10:09
This [change] (https://github.com/ilayaperumalg/spring-cloud-stream/commit/cee87ffb1cace5ebcdd60ea1cb6278b572f24025) tries to address one of the issues where the contentType is always set to `text/plain` even for the `application/json` contentType used at the producer. I guess the other thing to address is to `deduce` the expected type from the inbound adapter handler and perform automatic type conversion instead of doing

```
spring.cloud.stream.bindings.intput.content-type=application/x-java-object;type=demo.Vote
```

**Comment by dsyer** [comment] 2016-01-22 10:24
So there's a slightly orthogonal issue that the content type is ignored on the consumer. Should be easy to fix, but it won' solve the overall problem (if I read your comments correctly)? I looked at the code that does the conversion a bit because of an unrelated issue with spring boot devtools. I can see that `org.springframework.cloud.stream.binder.MessageChannelBinderSupport.deserializePayload(byte[], MimeType)` is the place where the initial deserialization happens. This is a couple of hops upstream of the `@ServiceActivator` but the information has to reach it somehow, so I guess it makes more sense for it to convert back to JSON, and then let something downstream deal with the JSON->POJO conversion? Would Spring Integration do that for us out of the box, or do we need to fix the dispatcher somehow? Could it be handled a layer above the default SpEL handler (so that faster, non-reflective handlers can be substituted and the same flow works)?

**Comment by mbogoevici** [comment] 2016-01-22 13:54
Making serialization the default strategy (i.e. absent any content type information) for transporting data is a legacy of Spring XD. Haven't looked at @ilayaperumalg 's change in detail, but in theory we could replace the default marshalling with a more portable format (e.g. JSON). 

The other issue though is that the dispatching process in Spring Integration is based purely on type information (so indeed a `String` cannot be converted by default to a `Vote`). The question here is how easy it is to swap (or augment) the current method invocation strategy so that the passed arguments can be populated based on information found in the entire message (i.e. the String payload + contentType headers). I think we need some guidance from @garyrussell here.

**Comment by dsyer** [comment] 2016-01-22 14:19
I don't object (much) to putting `contentType=application/json` in my config. So if we could persuade Spring Integration that it knows how to convert JSON to `Vote` we are winning?

**Comment by markpollack** [comment] 2016-01-22 15:02
Seems there are hooks for it - http://docs.spring.io/spring-xd/docs/current/reference/html/#mime-types-and-java-types

It this issue only wrt to json, or do we have something to address as well if we want to send protocol buffer payloads across the wire.  That was the original motivation to add custom converters here - http://docs.spring.io/spring-xd/docs/current/reference/html/#Providing-a-New-Type-Converter

**Comment by dsyer** [comment] 2016-01-22 15:05
IMO it shouldn't matter what the actual content type is as long as there is a sensible strategy for conversion from/to the POJOs in the handlers. It should be up to the user what content type is transported in the bytes over the wire, and he should have a reasonable expectation that it will be unpacked to a supported type in the consumer without doing anything (beyond maybe including the right converter on the classpath). I.e. I don't think there is anything JSON specific.

**Comment by ilayaperumalg** [comment] 2016-01-22 18:19
This [change](https://github.com/ilayaperumalg/spring-cloud-stream/commit/9152ce7d0c3e840139743328eacdab1cdb00b315) provides one possible approach to specify the input message type `programmatically` (as the developer would know what the input type would be when programming). 

While both commits on the branch depicts the underlying issue and rough approach to handle this, I will write a doc that can be discussed for designing a better solution.

**Closed** 2016-03-17 20:05 UTC
Labels: in pr

**Comment by GADNT** [comment] 2017-03-08 14:50
Hi guys

Maybe is not the good thread but I think is related to.
For the StreamListener annotation worked the case Json->Pojo, but for @Filter annotation on a method for a input channel that have content-type: application/json the transform is failing from JSON to POJO. If the producer have the binding content-type: application/json and the consumer have binding content-type: application/x-java-object;type=x.x.POJO then is working.
Have you encountered this in your tests? Any thoughts related to are much appreciated.
Thank you

**Comment by dsyer** [comment] 2017-03-08 15:06
`@Filter` is not a Spring Cloud Stream annotation. It does not support content negotiation.

**Comment by artembilan** [comment] 2017-03-08 15:10
The `@Filter` and other Messaging Annotations configuration, or even better - any POJO method invocation, will support content negotiation since Spring Integration 5.0: https://jira.spring.io/browse/INT-4225

**Comment by hamzaislam** [comment] 2017-05-25 06:37
We are producing AVRO message over Kafka from Spring Boot and trying to consume it with a NodeJS application, we find the AVRO data contains x-java-object as content type and isn't really a valid JSON for NodeJS for parse. 

anyone facing similar problem?

**Comment by ilayaperumalg** [comment] 2017-05-25 06:44
@hamzaislam When producing messages into non Spring Cloud Stream applications,  you would need to set `spring.cloud.stream.bindings.<channelName>.producer.headerMode=raw`. You can find documentation for this under ProducerProperties `headerMode`.

**Comment by ilayaperumalg** [comment] 2017-05-25 06:47
@hamzaislam Also, it is recommended to create a new Github question/issue or ask the question on StackOverflow [here](https://stackoverflow.com/questions/tagged/spring-cloud-stream) as this current Github issue is already closed.

**Comment by quercus-snappy** [comment] 2025-02-02 13:00
> Also, I think there is something we're missing when saying
> 
> > Let's just take the actual String as inbound payload case with 3 examples: JSON text, XML text, or plain ole text.
> 
> There is no `String` as payload. There are only "bytes". ie `[3c 3f 78 6d 6c 0a]` with `text/plain` could be seen as a `String`, but with `application/octet-stream` it's bytes, with `text/xml` it could be the start of an xml document, _etc._ My point being: when it's on the wire, it does not have a type _per se_. It is given a type by
> 
> 1. an accompanying "content type"  header (e.g. the `Content-Type` http header, external)
> 2. a header s-c-s sets, which may or may not be understood by the middleware the message flows in





https://lnkr.fun/bf76e4e
