### ISSUE TITLE
error registering ErrorMessageSendingRecoverer bean

### ISSUE THREAD

**Issue by dsukhoroslov** [spring-cloud/spring-cloud-stream#1905] opened 2020-02-07 10:02 UTC
Hi,

SCS v.3.0.1.RELEASE. I have a header exchange in RabbitMQ and a queue with two bindings on different header values to the exchange:
```
spring.cloud.stream.bindings.orders-ship-positions.destination=orders.order
spring.cloud.stream.bindings.orders-ship-positions.group=store.orders.update
spring.cloud.stream.rabbit.bindings.orders-ship-positions.consumer.exchange-type=headers
spring.cloud.stream.rabbit.bindings.orders-ship-positions.consumer.queue-name-group-only=true
spring.cloud.stream.rabbit.bindings.orders-ship-positions.consumer.queue-binding-arguments.changeType=SHIP_POSITIONS
##
spring.cloud.stream.bindings.orders-cancel-positions.destination=orders.order
spring.cloud.stream.bindings.orders-cancel-positions.group=store.orders.update
spring.cloud.stream.rabbit.bindings.orders-cancel-positions.consumer.exchange-type=headers
spring.cloud.stream.rabbit.bindings.orders-cancel-positions.consumer.queue-name-group-only=true
spring.cloud.stream.rabbit.bindings.orders-cancel-positions.consumer.queue-binding-arguments.changeType=CANCEL_POSITIONS
```
when app starts the first binding processed correctly, but the second one fails:
```
2020-02-06 07:09:57.599  INFO [storeservice,,,] 1 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: store.orders.update, bound to: orders.order
2020-02-06 07:09:57.601 DEBUG [storeservice,,,] 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Creating cached Rabbit Channel from AMQChannel(amqp://guest@10.233.7.254:5672/,2)
2020-02-06 07:09:57.601 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Exchange 'orders.order'
2020-02-06 07:09:57.603 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'store.orders.update'
2020-02-06 07:09:57.610 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Binding destination [store.orders.update (QUEUE)] to exchange [orders.order] with routing key []
2020-02-06 07:09:57.706 DEBUG [storeservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Changing consumers from 1 to 1
2020-02-06 07:09:57.707  INFO [storeservice,,,] 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'store.orders.update.errors' has 1 subscriber(s).
2020-02-06 07:09:57.707  INFO [storeservice,,,] 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'store.orders.update.errors' has 2 subscriber(s).
2020-02-06 07:09:57.707 DEBUG [storeservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Starting Rabbit listener container.
2020-02-06 07:09:57.708 DEBUG [storeservice,,,] 1 --- [orders.update-1] o.s.a.r.listener.BlockingQueueConsumer   : Starting consumer Consumer@44808c29: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2020-02-06 07:09:57.713 DEBUG [storeservice,,,] 1 --- [orders.update-1] o.s.a.r.listener.BlockingQueueConsumer   : Started on queue 'store.orders.update' with tag amq.ctag-3y-Qp69SFs_Lti0eqQ8C_A: Consumer@44808c29: tags=[[]], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@10.233.7.254:5672/,2), conn: Proxy@4f2e21d7 Shared Rabbit Connection: SimpleConnection@3cb8b037 [delegate=amqp://guest@10.233.7.254:5672/, localPort= 37392], acknowledgeMode=AUTO local queue size=0
2020-02-06 07:09:57.713  INFO [storeservice,,,] 1 --- [           main] o.s.i.a.i.AmqpInboundChannelAdapter      : started bean 'inbound.store.orders.update'
2020-02-06 07:09:57.713 DEBUG [storeservice,,,] 1 --- [pool-1-thread-4] o.s.a.r.listener.BlockingQueueConsumer   : ConsumeOK: Consumer@44808c29: tags=[[amq.ctag-3y-Qp69SFs_Lti0eqQ8C_A]], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@10.233.7.254:5672/,2), conn: Proxy@4f2e21d7 Shared Rabbit Connection: SimpleConnection@3cb8b037 [delegate=amqp://guest@10.233.7.254:5672/, localPort= 37392], acknowledgeMode=AUTO local queue size=0
2020-02-06 07:09:57.715  INFO [storeservice,,,] 1 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: store.orders.update, bound to: orders.order
2020-02-06 07:09:57.716 DEBUG [storeservice,,,] 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Creating cached Rabbit Channel from AMQChannel(amqp://guest@10.233.7.254:5672/,3)
2020-02-06 07:09:57.716 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Exchange 'orders.order'
2020-02-06 07:09:57.803 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'store.orders.update'
2020-02-06 07:09:57.805 DEBUG [storeservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Binding destination [store.orders.update (QUEUE)] to exchange [orders.order] with routing key []
2020-02-06 07:09:57.834 DEBUG [storeservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Changing consumers from 1 to 1
2020-02-06 07:09:58.002 ERROR [storeservice,,,] 1 --- [           main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:471)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:169)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:126)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
.............
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'store.orders.update.errors.recoverer' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'store.orders.update.errors.recoverer': There is already [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:927)
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:323)
.........
```

please suggest how to specify two bindings for the same queue.

Thanks, Denis

**Comment by olegz** [comment] 2020-02-07 10:17
I don't think this is supported. Perhaps I need more details, but you effectively attempt to register the bean that already exist with the same name. Can you actually explain from he business use case stand point what exactly are you trying to accomplish? It appears to me that this is some kind of routing case and what I am thinking is that there may be another way for doing it, but I need to better understand the use case.

**Comment by dsukhoroslov** [comment] 2020-02-07 11:28
There is 1 header exchange (orders.order) and 1 queue (store.orders.update). I need to get messages with headers['changeType'] = 'SHIP_POSITIONS' or headers['changeType'] = 'CANCEL_POSITIONS' from exchange to the queue. In order to get them I specified two bindings in my app properties. At app initialization the second binding fails. If I understand it correctly, SCS registers error-listener bean under the hood, but it use queue name for the bean name and fails to register bean with the same name twice. The full error stack is:
```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:471)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:169)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:126)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at ru.mp.services.store.server.StoreServiceApplication.main(StoreServiceApplication.java:18)
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'store.orders.update.errors.recoverer' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'store.orders.update.errors.recoverer': There is already [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:927)
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:323)
	at org.springframework.context.support.GenericApplicationContext.registerBean(GenericApplicationContext.java:471)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:691)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:643)
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:505)
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:124)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:417)
	... 24 common frames omitted
```

**Comment by olegz** [comment] 2020-02-07 11:30
. . . and you want to process those messages by different message handlers? In other  words `SHIP_POSITIONS` should be routed to one handler while `CANCEL_POSITIONS` to another. Do I understand it correctly?

**Comment by dsukhoroslov** [comment] 2020-02-07 11:37
well, it is not required, I just haven't found other way to specify two bindings. The structure of message is the same, so I can process them in the same handler or in two different..

**Comment by olegz** [comment] 2020-02-07 11:39
You are not answering my question. You keep asking about two bindings as if it is the only way and I am trying to actually understand your use case. Are you trying to have two different handlers to handle messages based on specific header?

**Comment by dsukhoroslov** [comment] 2020-02-07 11:41
no

**Comment by olegz** [comment] 2020-02-07 11:55
Then what is the reason you're trying to create two bindings to the same destination?

**Comment by dsukhoroslov** [comment] 2020-02-07 12:15
because I don't know how to specify what I need in one binding. Does SCS support a kind of 'or' or 'in' syntax for bindings? What I need is:
```
spring.cloud.stream.rabbit.bindings.orders.consumer.queue-binding-arguments.changeType in (SHIP_POSITIONS, CANCEL_POSITIONS)
```
And RabbitMQ does not provide possibility to do it in one binding also.

**Comment by olegz** [comment] 2020-02-07 12:19
ok, so you want to *only* consume messages with 'SHIP_POSITIONS' and `CANCEL_POSITIONS` changeType, correct?

**Comment by dsukhoroslov** [comment] 2020-02-07 12:28
yes

**Comment by olegz** [comment] 2020-02-07 12:33
So, this seems to be a pure RabbitMq question. The way I see it all you need to do is create a binding (in the console or CLI) from exchange to queue based on headerA and headerB and whatever else condition. This way you don't need to think about multiple bindings to the same destination.

**Comment by dsukhoroslov** [comment] 2020-02-07 12:45
well, it is easy to specify these two bindings in RabbitMQ console or via RabbitMQ direct API, but I'm looking the way to do it with SCS. 
Ok, may be it is possible to turn off that error-listener registration via some config param?

**Comment by olegz** [comment] 2020-02-07 12:58
Sorry, but I am still puzzled as to why would you want to delegate this to SCSt? What would you expect SCSt to do with messages having other header values arriving on the same destination (queue)?

Also, even if you were to somehow "turn off that error-listener" you should expect other issues. 

The concept of a binding is to _establish a bridge between broker destination (i.e., queue) and user code_. What you're proposing is that this responsibility is extended to handle functionality already supported out-of-the-box by the broker. This would create a different problem for us (aside form re-implementing existing functionality) when dealing with brokers that do not provide the concept of header-based routing/filtering, and so on. . .

**Comment by dsukhoroslov** [comment] 2020-02-07 13:17
Ah, I see. I use the 'binding' word in terms of connecting rules between queue and exchange, like this: https://www.rabbitmq.com/tutorials/tutorial-four-python.html. 
I'd like to do it with SCS to be able to create queues and exchanges dynamically (SCS does it with no problems) and bind them together.

**Comment by olegz** [comment] 2020-02-07 13:30
Yes, but as you already pointed out you've miss-interpreted the concept of binding in SCSt and what you actually thought it may be.

**Comment by dsukhoroslov** [comment] 2020-02-07 13:44
yep, I thought it is a _channel_ in SCS terms. Anyway, if we agree on terms now, is it possible to fix the behavior around error-listener somehow? If it seems the queue name is not unique may be the binding/channel name ('orders-ship-positions' and 'orders-cancel-positions' from my config above) would be better candidate for the error-listener bean name? Registering 'orders.ship.positions.errors.recoverer' and 'orders.cancel.positions.errors.recoverer' beans will not cause any issues.

**Comment by olegz** [comment] 2020-02-11 15:57
Again, there is nothing to fix other than possibly throw an exception with a message informing the user that you can not have more than one binding to the same destination. It has nothing to do with `error-listener`. In fact I may do exactly that.

**Comment by dsukhoroslov** [comment] 2020-02-12 09:00
ok, let's consider another scenario: we have two exchanges (exA, exB, with similar message structures) and one queue q1. And we want to get messages from both exchanges into the same queue (to serialize message processing, for instance). So we have to bind both exA, exB with q1. At the second binding we'll get the same error regarding error-listener bean registration...

**Comment by olegz** [comment] 2020-02-12 12:08
You bind both exchanges to the same queue and that's it. From the stream perspective you only have one queue.

**Comment by dsukhoroslov** [comment] 2020-02-12 23:42
yep, one queue but two bindings. just tried the following sample config:
```
#test bindings
spring.cloud.stream.bindings.test-bg1.destination=test.exa
spring.cloud.stream.bindings.test-bg1.group=test.q1
spring.cloud.stream.rabbit.bindings.test-bg1.consumer.exchange-type=headers
spring.cloud.stream.rabbit.bindings.test-bg1.consumer.queue-name-group-only=true
spring.cloud.stream.rabbit.bindings.test-bg1.consumer.queue-binding-arguments.changeType=TEST-1
#
spring.cloud.stream.bindings.test-bg2.destination=test.exb
spring.cloud.stream.bindings.test-bg2.group=test.q1
spring.cloud.stream.rabbit.bindings.test-bg1.consumer.exchange-type=headers
spring.cloud.stream.rabbit.bindings.test-bg2.consumer.queue-name-group-only=true
spring.cloud.stream.rabbit.bindings.test-bg2.consumer.queue-binding-arguments.changeType=TEST-1
```
and got the following output at app startup:
```
2020-02-12 23:25:42.226  INFO [ordersservice,,,] 1 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: test.q1, bound to: test.exa
2020-02-12 23:25:42.228 DEBUG [ordersservice,,,] 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Creating cached Rabbit Channel from AMQChannel(amqp://guest@10.233.49.222:5672/,4)
2020-02-12 23:25:42.229 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Exchange 'test.exa'
2020-02-12 23:25:42.233 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'test.q1'
2020-02-12 23:25:42.243 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Binding destination [test.q1 (QUEUE)] to exchange [test.exa] with routing key []
2020-02-12 23:25:42.307 DEBUG [ordersservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Changing consumers from 1 to 1
2020-02-12 23:25:42.308  INFO [ordersservice,,,] 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'test.q1.errors' has 1 subscriber(s).
2020-02-12 23:25:42.308  INFO [ordersservice,,,] 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'test.q1.errors' has 2 subscriber(s).
2020-02-12 23:25:42.309 DEBUG [ordersservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Starting Rabbit listener container.
2020-02-12 23:25:42.310 DEBUG [ordersservice,,,] 1 --- [      test.q1-1] o.s.a.r.listener.BlockingQueueConsumer   : Starting consumer Consumer@7d727123: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2020-02-12 23:25:42.314 DEBUG [ordersservice,,,] 1 --- [      test.q1-1] o.s.a.r.listener.BlockingQueueConsumer   : Started on queue 'test.q1' with tag amq.ctag-sSMKehO3BtZYTYzMWW6lVw: Consumer@7d727123: tags=[[]], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@10.233.49.222:5672/,4), conn: Proxy@45b4d2ff Shared Rabbit Connection: SimpleConnection@2ea3f905 [delegate=amqp://guest@10.233.49.222:5672/, localPort= 50066], acknowledgeMode=AUTO local queue size=0
2020-02-12 23:25:42.314 DEBUG [ordersservice,,,] 1 --- [pool-1-thread-4] o.s.a.r.listener.BlockingQueueConsumer   : ConsumeOK: Consumer@7d727123: tags=[[amq.ctag-sSMKehO3BtZYTYzMWW6lVw]], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@10.233.49.222:5672/,4), conn: Proxy@45b4d2ff Shared Rabbit Connection: SimpleConnection@2ea3f905 [delegate=amqp://guest@10.233.49.222:5672/, localPort= 50066], acknowledgeMode=AUTO local queue size=0
2020-02-12 23:25:42.314  INFO [ordersservice,,,] 1 --- [           main] o.s.i.a.i.AmqpInboundChannelAdapter      : started bean 'inbound.test.q1'
2020-02-12 23:25:42.316  INFO [ordersservice,,,] 1 --- [           main] c.s.b.r.p.RabbitExchangeQueueProvisioner : declaring queue for inbound: test.q1, bound to: test.exb
2020-02-12 23:25:42.318 DEBUG [ordersservice,,,] 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Creating cached Rabbit Channel from AMQChannel(amqp://guest@10.233.49.222:5672/,5)
2020-02-12 23:25:42.318 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Exchange 'test.exb'
2020-02-12 23:25:42.322 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : declaring Queue 'test.q1'
2020-02-12 23:25:42.323 DEBUG [ordersservice,,,] 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Binding destination [test.q1 (QUEUE)] to exchange [test.exb] with routing key [#]
2020-02-12 23:25:42.333 DEBUG [ordersservice,,,] 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Changing consumers from 1 to 1
2020-02-12 23:25:42.431 ERROR [ordersservice,,,] 1 --- [           main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:471)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143)
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:169)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:126)
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at ru.mp.services.orders.server.OrdersServiceApplication.main(OrdersServiceApplication.java:17)
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'test.q1.errors.recoverer' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'test.q1.errors.recoverer': There is already [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:927)
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:323)
	at org.springframework.context.support.GenericApplicationContext.registerBean(GenericApplicationContext.java:471)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:691)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:643)
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:505)
	at org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:124)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:417)
	... 24 common frames omitted
```

what was also interesting: the first exchange 'test.exa' was created in RabbitMQ as header exchange and bound to the 'test.q1' queue via header specified in the config, but the second exchange 'test.exb' was created as topic exchange and bound with routing key #.

**Comment by olegz** [comment] 2020-02-13 06:37
_yep, one queue but two bindings._ - as far as I see you have two queues `test.exa` (mapped to `test-bg1` binding) and `test.exb` (mapped to `test-bg2` binding). What am I missing?

**Comment by olegz** [comment] 2020-02-13 06:45
I still wish you would explain your use case instead of trying to explain _how_ you trying to implement _it_ where only you understand what _it_ is.
I mean can you say something like: 

_I have events sent to an event system which in my case is RabbitMQ. I need ti consume/process these events, but not all of the events, only the once that match certain criteria. How can I accomplish that?_ - something like that. In other words let's rewind and try to understand the _actual problem_ and not the _problem with a perceived solution_ which may be wrong.

**Comment by dsukhoroslov** [comment] 2020-02-13 08:46
> _yep, one queue but two bindings._ - as far as I see you have two queues `test.exa` (mapped to `test-bg1` binding) and `test.exb` (mapped to `test-bg2` binding). What am I missing?

![rabbit_ex](https://user-images.githubusercontent.com/5073945/74416522-521ce200-4e56-11ea-8fc2-48fa8749ae45.png)

this is from rabbitMQ console, exchanges tab

**Comment by olegz** [comment] 2020-02-13 08:48
in your configuration `test-bg2` exchange is not configured as 'headers` type

**Comment by dsukhoroslov** [comment] 2020-02-13 08:54
Ah, sorry for the typo. it explains why the second exchange is of topic type. But the bean registration issue is still there.
Oleg, the discussion becomes quite long. May be we'll continue it in direct email? My box: dsukhoroslov at gmail dot com.

**Comment by olegz** [comment] 2020-02-13 09:07
There is nothing to continue as you are not answering my questions causing the discussion to be this long. By ignoring my questions you effectively insist that the solution you're proposing is correct and that there are some issues in stream. In theory this may or may not be correct, but until you actually explain your problem without using the words _binding, stream, spring, bean registration, etc.,_ we don't know it thus there is nothing else to discuss. 

Once again, spring-cloud-stream _binding_ is a 1:1 map between *broker destination* and *user code*. The 1:1 relationship is by design.

**Comment by dsukhoroslov** [comment] 2020-02-13 09:23
I stated the problem at the very beginning of this discussion: "There is 1 header exchange (orders.order) and 1 queue (store.orders.update). I need to get messages with headers['changeType'] = 'SHIP_POSITIONS' or headers['changeType'] = 'CANCEL_POSITIONS' from exchange to the queue".

**Comment by olegz** [comment] 2020-02-13 15:30
You're still not answering my question about explaining the actual business problem, so be it. . .

You're effectively asking how to bind single Rabbit queue to two header values in OR relationship in Rabbit headers exchange. And while this specific question is out of scope of spring-cloud-stream all together i'll answer it anyway, so I can close this issue.

You simply create multiple bindings from a single exchange to a single queue using Rabbit Admin functionality (i.e., via CLI, API or Management Console as shown below).

<img width="537" alt="Screenshot 2020-02-13 at 16 22 38" src="https://user-images.githubusercontent.com/172397/74449625-1ba68d80-4e7d-11ea-8abc-56288595f81a.png">

**Closed by olegz** 2020-02-13 15:30 UTC
Labels: question
