### ISSUE TITLE
Kafka producer losing messages during shutdown while using asynchronous processing 

### ISSUE THREAD

**Issue by akhalifeh79** [spring-cloud/spring-cloud-stream#2888] opened 2024-01-23 08:59 UTC
I am using Spring Cloud Stream Kafka Binder to produce message into Kafka. I kept producer sync to false and defined a batch Timeout. During shutdown of the system( where the producer is running) messages existing in the buffer are not sent and consequently getting lost.  

This is the context:

- Spring boot 3

- Graceful shutdown is  configured as follows: 
 server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=4m

- Spring cloud version as follows: 
    <parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>2022.0.4</version>
   </parent>

- Producer configuration
spring.cloud.stream.kafka.default.producer.sync=false
spring.cloud.stream.kafka.default.producer.batchTimeout=60000
spring.cloud.stream.kafka.default.producer.compression=gzip
spring.cloud.stream.kafka.default.producer.bufferSize=124000

**Comment by sobychacko** [comment] 2024-01-23 16:22
Is this behavior consistent? Are there any predictable ways to reproduce the issue? If you can provide a sample app and instructions to reproduce it, that will help triage the issue further.

**Comment by akhalifeh79** [comment] 2024-01-26 14:10
> Is this behavior consistent across runs? Are there any predictable ways to reproduce the issue? If you can provide a sample app and instructions to reproduce it, that will help triage the issue further.

Hi, this is reproduceable on any app using kafka producer. Just follow these steps:
- add the configuration listed above related to producer configuration in application.properties file 
- invoke your kafka producer to send some topics/messages 
- shutdown the system gracefully N milliseconds before the precedent event where N = spring.cloud.stream.kafka.default.producer.batchTimeout
- using kafka client like offset explorer check if the producer has sent the messages. 

If needed I will create an app from scratch. 
Thanks

**Comment by sobychacko** [comment] 2024-01-26 22:59
If you could provide a simple app, that would be really helpful.

**Comment by sobychacko** [comment] 2024-01-31 16:31
@akhalifeh79 Any updates?

**Comment by akhalifeh79** [comment] 2024-02-07 11:20
Please see the project: 
https://github.com/akhalifeh79/kafka-producer.async/tree/master

Follow these steps to reproduce the issue:
- Download the project
- Configure kafka endpoints in application.properties  to your own kafka server
- Run the spring boot application
- Send a kafka message by calling the url http://localhost:9012/send
- Batch time out is configured for 1 minute, if you wait for one minute a kafka topic will be sent as expected to spring.stream.kafka.producer.test topic.
- Send again a kafka topic and shutdown the app gracefully & immediately after messsage sending. Result: Kafka message is lost.

**Comment by akhalifeh79** [comment] 2024-02-07 11:31
With spring cloud new version seems functioning, the message is sent immediately during shutdown. 
<spring-cloud.version>2023.0.0</spring-cloud.version>
I will test and update you.

**Comment by sobychacko** [comment] 2024-02-07 14:40
@akhalifeh79 Please confirm. There is nothing specific that went into the latest GA that may be related to this issue, but I am glad to hear that the issue is not present with the latest.

**Comment by akhalifeh79** [comment] 2024-02-08 08:21
I do confirm 
with this version 
<spring-cloud.version>2022.0.0</spring-cloud.version>
the app is loosing buffered messages during shutdown 
while the version
<spring-cloud.version>2023.0.0</spring-cloud.version>
fixed the problem.

**Comment by akhalifeh79** [comment] 2024-02-14 09:50
@sobychacko just an update. 
upgrading from 
<spring-cloud.version>2022.0.**4**</spring-cloud.version>
to 
<spring-cloud.version>2022.0.**5**</spring-cloud.version>
the problem is solved.

**Comment by sobychacko** [comment] 2024-02-15 00:26
@akhalifeh79 Thanks for that update. In that case, the problem is resolved in a point release. Can you upgrade to that latest point release? I am closing the issue. Please feel free to re-open if necessary.

**Closed by sobychacko** 2024-02-15 00:26 UTC
Labels: waiting-on-feedback, waiting-for-confirmation
