### ISSUE TITLE
Dispatcher has no subscribers for channel

### ISSUE THREAD

**Issue by azmym** [spring-cloud/spring-cloud-stream#1349] opened 2018-04-05 16:58 UTC
I developed new service using spring cloud stream and it was working fine, and suddenly I got the following Error 
```
ERROR o.s.i.handler.LoggingHandler - org.springframework.messaging.MessageDeliveryException: 
Dispatcher has no subscribers for channel 'application.inputTopic'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[3287], headers={kafka_offset=438359, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3a13bf52, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=[B@5f4d910d, kafka_receivedPartitionId=3, kafka_receivedTopic=products, kafka_receivedTimestamp=1522912482308, kafka_acknowledgment=Acknowledgment for ConsumerRecord(topic = products, partition = 3, offset = 438359, CreateTime = 1522912482308, serialized key size = 36, serialized value size = 3287, headers = RecordHeaders(headers = [], isReadOnly = false), key = [B@5f4d910d, value = [B@74acd088), contentType=application/json}], failedMessage=GenericMessage [payload=byte[3287], headers={kafka_offset=438359, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3a13bf52, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=[B@5f4d910d, kafka_receivedPartitionId=3, kafka_receivedTopic=marketplace.products, kafka_receivedTimestamp=1522912482308, kafka_acknowledgment=Acknowledgment for ConsumerRecord(topic = products, partition = 3, offset = 438359, CreateTime = 1522912482308, serialized key size = 36, serialized value size = 3287, headers = RecordHeaders(headers = [], isReadOnly = false), key = [B@5f4d910d, value = [B@74acd088), contentType=application/json}]\
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)\
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:463)\
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:407)\
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)\
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)\
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)\
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)\
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)\
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:69)\
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:376)\
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:353)\
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120)\
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)\
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)\
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114)\
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40)\
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1001)\
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:981)\
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:932)\
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:801)\
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689)\
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)\
	at java.lang.Thread.run(Thread.java:745)\ 
```
and this is my configuration 
```
@Component
public interface BinderProcessor {
    @Input
    SubscribableChannel inputTopic();
    @Output
    MessageChannel outputTopic();
}
```
```
@Component
@EnableBinding(BinderProcessor.class)
public class Consumer {

    private static final Logger LOG = LoggerFactory.getLogger(Consumer.class);

    private final BinderProcessor binderProcessor;

    @Autowired
    public Consumer(final BinderProcessor binderProcessor) {
        this.binderProcessor = binderProcessor;
    }

    public Flux<ProductDifferenceModel> consume() {

        LOG.debug("attache new consumer to kafka topic");

        return Flux.create(fluxSink -> {
            MessageHandler handler = message -> fluxSink.next(new ProductDifferenceModel(JsonConverter.convert((byte[]) message.getPayload()),
                    (Acknowledgment) message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class)));
            binderProcessor.inputTopic().subscribe(handler);
            fluxSink.onCancel(()-> binderProcessor.inputTopic().unsubscribe(handler));
        });

    }

}
```
application.properties

```
#Kafka configuration
spring.kafka.bootstrap-servers=192.168.99.100:9092
#Binder Configuration
spring.cloud.stream.kafka.binder.brokers=192.168.99.100
spring.cloud.stream.kafka.binder.defaultBrokerPort=9092
spring.cloud.stream.kafka.binder.zkNodes=192.168.99.100

spring.cloud.stream.bindings.inputTopic.destination=products
spring.cloud.stream.kafka.bindings.inputTopic.consumer.autoCommitOffset=false

spring.cloud.stream.bindings.outputTopic.destination=test
```

pom.xml

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.0.RELEASE</version>
	<relativePath/> <!-- lookup parent from repository -->
</parent>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-stream-kafka</artifactId>
</dependency>

<spring-cloud.version>Finchley.M6</spring-cloud.version>

<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
     </dependencies>
</dependencyManagement>
```

**Comment by artembilan** [comment] 2018-04-05 17:09
@azmym ,

We need to see where you call `Flux<ProductDifferenceModel> consume()`.

Typical error to start to produce message too early, before the real subscription to the `MessageChannel` happens. Usually people do that in the `@PostProcess` or some other `afterPropertiesSet()`.

The proper way to do that from some `Lifecycle.start()`.

So, share your calling code, please, and we will advice you how to proceed.

Thanks

**Comment by azmym** [comment] 2018-04-05 17:36
@artembilan 
this is the calling hierarchy

```
@SpringBootApplication
@EnableReactiveMongoRepositories
public class ProductApplication {

	public static void main(String[] args) {
		SpringApplication.run(ProductApplication.class, args);
	}

	@Bean
	CommandLineRunner init(FlowManager flowManager){
		return args -> {
			flowManager.manage();
		};
	}
}
``` 

and this the flowMangerClass

```
@Component
public class FlowManager extends BasicFlow {
  private final Consumer consumer;
  
  @Autowired
   public FlowManager(final Consumer consumer){
    this.consumer = consumer;
  }

public void manage() {
Flux<ProductDifferenceModel> flux = consumer.consume();
//some business logic
}
}
```

**Comment by artembilan** [comment] 2018-04-05 17:57
That's exactly what I meant! You can't start consuming from the `CommandLineRunner`. That's still early in the application context lifecycle.

You should consider to move that `flowManager.manage()` code to the `main()`:
```
ApplicationContext applicationContext = SpringApplication.run(ProductApplication.class, args);
applicationContext.getBean(FlowManager.class).manage();
```

Also you can consider to use `@StreamEmitter` instead for such a Reactor-based stuff: https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC3/reference/htmlsingle/#_reactive_sources

@sabbyanandan , @sobychacko , we need to consider to add a `@StreamEmitter` `source` sample: https://github.com/spring-cloud/spring-cloud-stream-samples

Thanks

**Comment by azmym** [comment] 2018-04-06 08:39
Thanks @artembilan

**Comment by artembilan** [comment] 2018-04-06 13:26
May we close the issue as fixed already, @azmym ?

Hope my explanation was helpful.

**Closed** 2018-04-06 21:59 UTC

**Comment by azmym** [comment] 2018-04-17 20:47
@artembilan the error start to fire again after 11 days from apply the suggested solution , any other advice please

**Comment by artembilan** [comment] 2018-04-17 20:53
I don't think that it is the same error though...

Would be great if you can share with us some simple project to let us to play with it and possibly to reproduce an issue.

**Comment by azmym** [comment] 2018-04-17 21:18
it is the same error 
```
ERROR o.s.i.handler.LoggingHandler - org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.inputTopic'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[3269], headers={kafka_offset=486685, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@300a8edc, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=[B@1b5a4f1e, kafka_receivedPartitionId=8, kafka_receivedTopic=products, kafka_receivedTimestamp=1523601741166, kafka_acknowledgment=Acknowledgment for ConsumerRecord(topic = products, partition = 8, offset = 486685, CreateTime = 1523601741166, serialized key size = 36, serialized value size = 3269, headers = RecordHeaders(headers = [], isReadOnly = false), key = [B@1b5a4f1e, value = [B@3a7334a1), contentType=application/json}], failedMessage=GenericMessage [payload=byte[3269], headers={kafka_offset=486685, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@300a8edc, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=[B@1b5a4f1e, kafka_receivedPartitionId=8, kafka_receivedTopic=products, kafka_receivedTimestamp=1523601741166, kafka_acknowledgment=Acknowledgment for ConsumerRecord(topic = products, partition = 8, offset = 486685, CreateTime = 1523601741166, serialized key size = 36, serialized value size = 3269, headers = RecordHeaders(headers = [], isReadOnly = false), key = [B@1b5a4f1e, value = [B@3a7334a1), contentType=application/json}]\n	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)\n	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:463)\n	at org.springframework.integra
````

**Comment by artembilan** [comment] 2018-04-17 21:48
Well, without your custom project we can't help you.

I see you have the code like:
```
fluxSink.onCancel(()-> binderProcessor.inputTopic().unsubscribe(handler));
```

So, maybe your application meets some condition when it really *cancel* a subscription to that `Flux`, therefore you drop a subscriber to the `inputTopic` channel and not able to process any new consumed message from the topic.

It looks like this ticket turns out far away from Framework issue. 
Would better to move it into some community forum, e.g. StackOverflow.
