### ISSUE TITLE
I just sent to provider error channel

### ISSUE THREAD

**Issue by jarjune** [spring-cloud/spring-cloud-stream#2093] opened 2021-01-27 08:30 UTC
I am subscribe to either error channel with a @ServiceActivator to handle errors,
an ErrorMessage is sent to the comsumer error channel (\<destination\>.\<group\>.errors),
an ErrorMessage is sent to the provider error channel (\<destination\>.errors)

when i send ErrorMessage to provider error channel, `org.springframework.integration.dispatcher.RoundRobinLoadBalancingStrategy.buildHandlerIterator` will load balancing with global error channel(IntegrationContextUtils.ERROR_CHANNEL_BEAN_NAME)

for example

```java
    @StreamListener(IntegrationContextUtils.ERROR_CHANNEL_BEAN_NAME)
    public void handleError(ErrorMessage errorMessage) throws Exception {
         logger.error("[global]");
    }
    @ServiceActivator(inputChannel = "provider-test.errors")
    public void handleError1(ErrorMessage errorMessage) throws Exception {
         logger.error("[provider1]");
    }
    @ServiceActivator(inputChannel = "provider-test.errors")
    public void handleError2(ErrorMessage errorMessage) throws Exception {
         logger.error("[provider2]");
    }
```

the order of sent to error channel
1. provider1
2. provider2
3. global
4. provider1
5. provider2
6. ...

But I just sent to provider error channel

**Comment by garyrussell** [comment] 2021-01-27 16:03
This was fixed in 3.1.0: https://github.com/spring-cloud/spring-cloud-stream/issues/2021

To work around it in previous versions explicitly define the error channel as a `@Bean` of type `PublishSubscribeChannel`.

**Comment by jarjune** [comment] 2021-01-28 02:30
I want send to provider1 or provider2 error channel，don't send global error channel.

however，
first send, the console print provider1,
second send, the console print provider2,
**third send, the console print global**

**Comment by jarjune** [comment] 2021-01-28 02:30
I want send to provider1 or provider2 error channel，don't send global error channel.

however，
first send, the console print provider1,
second send, the console print provider2,
third send, the console print global

**Comment by garyrussell** [comment] 2021-01-28 15:54
Each binding error channel is bridged to the global `errorChannel` to enable users to consume all errors from the global error channel or the individual channels.

By default, the global error channel has a logging adapter subscribed to it.

You can't prevent the bridge, but you can define your own.

```
@Bean
PublishSubscribeChannel errorChannel() {
    return new PublishSubscribeChannel();
}
```

It will replace the default error channel and have no subscribers.

**Comment by jarjune** [comment] 2021-01-28 16:41
bridged to the global errorChannel it's ok,

see `org.springframework.integration.dispatcher.RoundRobinLoadBalancingStrategy.buildHandlerIterator`

![image](https://user-images.githubusercontent.com/19874732/106168907-c1a3f280-61c9-11eb-854d-01a757e45677.png)

why global errorbridge in loadBalancingStrategy，Shouldn't the bridge in last? when i defined provider error channel throws Exception, then bridge can be used?

**Comment by garyrussell** [comment] 2021-01-28 17:32
The problem I mentioned here https://github.com/spring-cloud/spring-cloud-stream/issues/2093#issuecomment-768388810 was caused by the the `@ServiceActivator` creating a `DirectChannel`. This. caused an incorrect round-robin between the local error channel and global error channel. If the channel doesn't exist already, the binder creates a pub/sub channel.

This was incorrect and the work-around was to define the channel as a `PublishSubcribeChannel` and that made it work as expected.

The binder was subsequently changed in 3.1 to detect if it's a `DirectChannel` and, instead, add a bridge to the global error channel so that both the local and global error channels again get the message.

As I said, the only way to get your desired behavior is to override the `errorChannel` with one that has no subscribers.

**Comment by garyrussell** [comment] 2021-01-28 17:36
The problem I mentioned here https://github.com/spring-cloud/spring-cloud-stream/issues/2093#issuecomment-768388810 was caused by the the `@ServiceActivator` creating a `DirectChannel`. This. caused an incorrect round-robin between the local error channel and global error channel. If the channel doesn't exist already, the binder creates a pub/sub channel.

This was incorrect and the work-around was to define the channel as a `PublishSubcribeChannel` and that made it work as expected.

The binder was subsequently changed in 3.1 to detect if it's a `DirectChannel` and, instead, add a bridge to the global error channel so that both the local and global error channels again get the message.

There is no way to get your desired behavior is to override the `errorChannel` with one that has no subscribers.

**Comment by garyrussell** [comment] 2021-01-28 17:36
The problem I mentioned here https://github.com/spring-cloud/spring-cloud-stream/issues/2093#issuecomment-768388810 was caused by the the `@ServiceActivator` creating a `DirectChannel`. This. caused an incorrect round-robin between the local error channel and global error channel. If the channel doesn't exist already, the binder creates a pub/sub channel.

This was incorrect and the work-around was to define the channel as a `PublishSubcribeChannel` and that made it work as expected.

The binder was subsequently changed in 3.1 to detect if it's a `DirectChannel` and, instead, add a bridge to the global error channel so that both the local and global error channels again get the message.

There is no way to get your desired behavior.

**Comment by garyrussell** [comment] 2021-01-28 17:38
The problem I mentioned here https://github.com/spring-cloud/spring-cloud-stream/issues/2093#issuecomment-768388810 was caused by the the `@ServiceActivator` creating a `DirectChannel`. This. caused an incorrect round-robin between the local error channel and global error channel. If the channel doesn't exist already, the binder creates a pub/sub channel.

This was incorrect and the work-around was to define the channel as a `PublishSubcribeChannel` and that made it work as expected.

The binder was subsequently changed in 3.1 to detect if it's a `DirectChannel` and, instead, add a bridge to the global error channel so that both the local and global error channels again get the message.

The only way I can think of to get your desired behavior is to subscribe 2 bridge handlers to the global error channel, bridging to 2 new channels consumed by your services.

**Comment by garyrussell** [comment] 2021-01-28 17:39
The problem I mentioned here https://github.com/spring-cloud/spring-cloud-stream/issues/2093#issuecomment-768388810 was caused by the the `@ServiceActivator` creating a `DirectChannel`. This. caused an incorrect round-robin between the local error channel and global error channel. If the channel doesn't exist already, the binder creates a pub/sub channel.

This was incorrect and the work-around was to define the channel as a `PublishSubcribeChannel` and that made it work as expected.

The binder was subsequently changed in 3.1 to detect if it's a `DirectChannel` and, instead, add a bridge to the global error channel so that both the local and global error channels again get the message.

The only way I can think of to get your desired behavior is to define the global `errorChannel` as a `DirectChannel` and subscribe 2 bridge handlers to the global error channel, bridging to 2 new channels consumed by your services (instead of the built-in-

**Comment by jarjune** [comment] 2021-01-29 12:06
Do you have a Demo(before 3.1 version)? this seems any error be sent all "subscribe channel", can't judge this error from which one provider?

emmm....
I'm created Spring Cloud Stream 3.1 demo project, and Debugger, It's ok(don't round-robin between the local error channel and global error channel)

**Closed** 2021-03-09 06:08 UTC
Labels: waiting-on-feedback
