### ISSUE TITLE
spring-cloud-stream-binder-rabbit behaves like a queue when using topic

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-stream#190] opened 2015-11-02 23:47 UTC
See https://github.com/spring-cloud/spring-cloud-bus/issues/21 for details.  You can use [customer-stores](https://github.com/spring-cloud-samples/customers-stores) as a working example of the problem. If I switch it to redis, it works fine.

**Comment by spencergibb** [comment] 2015-11-03 00:30
@sabbyanandan did you see my comment in #193?

**Comment by garyrussell** [comment] 2015-11-03 12:41
The issue is because the queue bound by the tap consumer to the fanout does not include the name of the consumer (in XD, the tapping stream name [group] was part of the queue name - this allows competing consumers by multiple instances of the same tap stream while each tap stream gets its own queue).

In s-c-s; since the queue no longer contains the consumer group, all consumers are competing for messages.

**Comment by garyrussell** [comment] 2015-11-03 15:43
@sabbyanandan Should we move this into the sprint or close it?

**Comment by sabbyanandan** [comment] 2015-11-03 17:02
I missed this one. Thanks @spencergibb.

@garyrussell: Your primary PR would address this scenario anyway; so, closing this.

**Closed by sabbyanandan** 2015-11-03 17:02 UTC
