### ISSUE TITLE
partitionKeyExpression=headers['kafka_messageKey'] is not sending messages to right partition

### ISSUE THREAD

**Issue by ahmed-ali225** [spring-cloud/spring-cloud-stream#1787] opened 2019-08-21 15:18 UTC
Hi,

I'm using the `partitionKeyExpression=headers['kafka_messageKey']` property in my application.properties for the producer to my kafka topic, but this is not working correctly and messages with the same key are not going to the same partition as expected.

In my code i'm setting the key as in below:
```
return MessageBuilder.withPayload(message.getPayload())
                            .setHeader(KafkaHeaders.MESSAGE_KEY, message.getKey().getBytes())
                            .build();
```

on the other hand, if i change the expression to: `partitionKeyExpression=payload.key`
it works as expected.

**Comment by olegz** [comment] 2019-08-22 11:53
Hmm, I am not sure what `Message` api you are using as there is no `key` attribute on the `Message`, so please clarify. 
Also, looking at your code `payload.key` and `headers['kafka_messageKey']` most certainly render different values.
In first you use `key` attribute of the `payload` in other `key` attribute of a `message` (  `message.getKey().getBytes()`  ). 
Anyway, please clarify

**Comment by ahmed-ali225** [comment] 2019-08-22 12:34
Sorry, for not being clear will try to clarify more in this comment.

 The `message` variable is just an instance of a dto i have and the "payload"  property in it is just of type `JsonNode` and the "key" property is a `String` set in the same dto and then the whole dto is being sent as a message, so the key i'm referring to in my SpEL is having the very same value.

So, the key value i could see correctly set in the headers in both cases...the issue is that i don't know why Spring is not redirecting messages correctly to partitions when i use `partitionKeyExpression=headers['kafka_messageKey']`.

Example for clarification, suppose that i have a topic with 5 partitions and i need all messages with the same key to be sent to the same partition automatically as this key could be an order Id or so
and this is to keep the order of the messages came in with an evolving state of the same order so that log compaction can work correctly later on and keep the latest message with the latest state of my order.

messages with key 123 -> partition 4
messages with key 456 -> partition 3

this works fine if i use the key property set in my dto/payload as in below:
`partitionKeyExpression=payload.key`

**Comment by olegz** [comment] 2019-09-11 13:32
I can't reproduce it, so perhaps you can generate a small project where it is reproducible so we can look

**Comment by olegz** [comment] 2019-09-24 13:06
Closing it due to the lack of follow up from the original reporter. Please fell free to re-open it if more details are provided

**Closed by olegz** 2019-09-24 13:06 UTC
Labels: waiting-on-feedback
