### ISSUE TITLE
Issue with exchange type reading from properties file

### ISSUE THREAD

**Issue by kartik-kaushik** [spring-cloud/spring-cloud-stream#2705] opened 2023-04-12 17:22 UTC
Hi team,
Getting issue with the code described below:

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
      <version>4.0.3-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-stream-binder-rabbit-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-stream</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-rabbit-core</artifactId>
      <version>4.0.3-SNAPSHOT</version>
    </dependency>

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream</artifactId>
      <version>4.0.3-SNAPSHOT</version>
    </dependency>

we are using exchangeType fanout but it is always taking topic. But same properties are working fine in non-native app
```yaml
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          emailevent-out-0:
            producer:
              routingKeyExpression: '''events.in'''
              exchangeType: direct
              use-confirm-header: true
          audit-out-0:
            producer:
              exchangeType: fanout
              use-confirm-header: true
      default-binder: binder1
      binders:
        binder1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: virtual-host1
                host: localhost
                port: 5672
                username: guest
                password: guest
                ssl:
                  enabled: false
        binder2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: virtual-host2
                host: localhost
                port: 5672
                username: guest
                password: guest
                ssl:
                  enabled: false
      bindings:
        audit-out-0:
          producer:
            error-channel-enabled: true
          binder: binder1
          destination: domain.events
        emailevent-out-0:
          binder: binder2
          destination: domain.events2
```
error:
inequivalent arg 'type' for exchange 'domain.events' in vhost 'virtual-host1': received 'topic' but current is 'fanout'

Kindly help in resolution of the same.

**Comment by garyrussell** [comment] 2023-04-12 17:49
>`inequivalent arg 'type' for exchange 'domain.events' in vhost 'virtual-host1': received 'topic' but current is 'fanout'`

Exchanges, queues etc are immutable once created; you can't change an exchange type; it must be deleted first and re-created.

**Comment by garyrussell** [comment] 2023-04-12 18:02
I just copied your YAML into a new application (Boot 3.0.5, Cloud 2022.0.2) and the exchanges were created correctly...

<img width="378" alt="Screenshot 2023-04-12 at 2 00 55 PM" src="https://user-images.githubusercontent.com/483832/231544857-a172bcda-1ae8-4487-8c21-11c7d446d638.png">

**Comment by kartik-kaushik** [comment] 2023-04-13 04:00
@garyrussell Kindly try to publish the message. Sharing you the code for same. The code is working fine as non-native but giving issue in native.

public void publishMessages(Object event) {
    try {
      Message<Object> eventDetailsMessage = MessageBuilder.withPayload(event).build();
      this.bridge.send("emailevent-out-0", eventDetailsMessage);
    } catch (Exception ex) {
      ex.printStackTrace();
      throw ex;
    }

  }

Error received:
inequivalent arg 'type' for exchange 'domain.events' in vhost 'virtual-host1': received 'topic' but current is 'direct'

**Comment by garyrussell** [comment] 2023-04-13 13:23
Sorry, I didn't see that comment (about native).

I have no idea why the properties are not applied using native. @olegz @sobychacko any ideas?

**Comment by jhornakova** [comment] 2023-04-14 06:54
Hi, i have the similar issue. The problem is, that native build cannot load configuration from application.yml because of missing classes or proper constructors.

As workaround try adding this annotation to some component. Worked for me.

```
@RegisterReflectionForBinding({
    RabbitProducerProperties.class,
    RabbitConsumerProperties.class,
    RabbitBindingProperties.class
})
```

**Comment by kartik-kaushik** [comment] 2023-04-14 17:09
@jhornakova thanks....I added those and the above error is done but now I am getting the below as my properties are:
emailevent-out-0:
            producer:
              routingKeyExpression: '''events.in'''
              exchangeType: direct
              use-confirm-header: true

@olegz @sobychacko 
Could you please help as the error post the above solution is as :
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.emailevent-out-0.producer.routing-key-expression' to org.springframework.expression.Expression

Let me know if anything else is needed.
Thanks

**Comment by onobc** [comment] 2023-04-14 20:43
> Hi, i have the similar issue. The problem is, that native build cannot load configuration from application.yml because of missing classes or proper constructors.
> 
> As workaround try adding this annotation to some component. Worked for me.
> 
> ```
> @RegisterReflectionForBinding({
>     RabbitProducerProperties.class,
>     RabbitConsumerProperties.class,
>     RabbitBindingProperties.class
> })
> ```

@jhornakova good find on `RegisterReflectionForBinding`. We need to get this added into the binder codebases (`rabbit/kafka/**`) and be sure we have coverage for this case in our AOT smoke tests.

**Comment by onobc** [comment] 2023-04-14 20:46
@kartik-kaushik it looks like the next issue (hopefully your last hurdle) is related to the binder child context not having the proper converters registered. 

@olegz @sobychacko we do set the converters from the parent context [here](https://github.com/spring-cloud/spring-cloud-stream/blob/0b5ae251f972865445b4cb753e2fcc8da11deb8e/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L420) but it seems they may not be available when running in AOT mode. This is the place to start debugging. 

@jhornakova @kartik-kaushik thanks for your patience and help as we knock the kinks out of the AOT side of this. We tested most of the scenarios but missed a few as well (that is the nature of AOT/testing). Rest assured that the issues we find here will be incorporated into our test suites to avoid regressions in the future.

**Closed** 2023-04-18 13:32 UTC
Labels: bug, AOT / NATIVE
