### ISSUE TITLE
Investigate bean override for ServerController

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1448] opened 2018-08-20 14:18 UTC
Relates to AvroSchemaRegistry support.

**Comment by olegz** [comment] 2018-08-23 04:34
I just had to take a look at it while working on another problem and it appears that `ServerController` bean declared in `SchemaServerConfiguration` is completely redundant as it doesn't override anything nor it provides any extra features/functionality. So simply removing it from `SchemaServerConfiguration` is all that is needed IMO.

**Comment by sabbyanandan** [comment] 2018-09-11 14:32
It appears the sample breaks when we remove the bean definition. Let's retest and verify.

**Comment by sobychacko** [comment] 2018-11-14 16:31
Since there is no `EnableAutoConfiguration` on `ServerController`, I believe it is required to redefine the controller bean in `ScheamaServerConfiguation`. cc/ @olegz 
Since it is working the way it is defined right now, I am closing this issue.

**Comment by olegz** [comment] 2019-01-22 15:01
Actually the problem is that at the moment one can no longer start `SchemaRegistryServerApplication` as it fails with override warning. I think the real issue is that `ServerController` is a `@Component` already, so bootstrapping it as a bean is meaningless and instead we should simply include it as `@Import`

**Closed** 2019-01-22 15:15 UTC
Labels: backport-2.1.x, bug
