### ISSUE TITLE
@StreamListener is not registered when app is in lazy init setup

### ISSUE THREAD

**Issue by przem** [spring-cloud/spring-cloud-stream#1768] opened 2019-07-19 21:59 UTC
Hey, 

I've observed that handlers marked with @StreamListener are not registered as beans i the context when spring.main.lazy-initialization is set to true.

There is an exception thrown indicating that the listener was not registered:

`org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139)`

Happens for me with spring-cloud-stream:3.0.0.M2

Workaround is to set lazy initialization to false.

**Comment by olegz** [comment] 2019-07-22 05:16
Well, this is technically by design, so I am nit sure if we should/can do anything about it. Not initialising/starting StreamListener kind of negates the whole purpose of the stream app.

Are you explicitly setting `lazy-initialization` to false in your app or you inherited it from some other config?

**Comment by olegz** [comment] 2019-07-30 12:03
I am going to close this as this is really by design. StreamListeners are not referenced explicitly hence not context is marked `spring.main.lazy-initialization` they are not initialzed.

**Closed by olegz** 2019-07-30 12:03 UTC
Labels: discussion-required

**Comment by gonzalad** [comment] 2019-10-28 15:05
A little late fot this answer sry...

If someone encounters the same issue (aka someone wishes to set spring.main.lazy-initialization=true while using @StreamListener), then just set @Lazy(false) to your streamListener beans

i.e.

```
@Component
@Lazy(false)
public classSomeBeanListener {

    @StreamListener(target = SomeBeanBinding.SOME_BEAN)
    public void handleMessage(@Valid SomeBean bean) {
    }
}
```

you can use spring.main.lazy-initialization=true if you annotate
