### ISSUE TITLE
4.2.0-RC1: NoSuchMethodError: org.springframework.integration.support.MessageBuilder.removeHeader(java.lang.String)

### ISSUE THREAD

**Issue by asantare** [spring-cloud/spring-cloud-stream#3047] opened 2024-11-25 08:57 UTC
spring-cloud-stream 4.2.0-RC1 fails with NoSuchMethodError when an AMQP message is received.

Probably because the missing method has been moved to a super-class in spring-integration 6.4.0.

I've been using new spring-boot `3.4.0` from "https://start.spring.io/" which uses the spring-cloud `2024.0.0-RC1`.

Here the partial `build.gradle.kts`:

```gradle
plugins {
	java
	id("org.springframework.boot") version "3.4.0"
	id("io.spring.dependency-management") version "1.1.6"
}

...

extra["springCloudVersion"] = "2024.0.0-RC1"

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	implementation("org.springframework.cloud:spring-cloud-function-context")
	implementation("org.springframework.cloud:spring-cloud-stream-binder-rabbit")
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
	}
}
```

**Comment by artembilan** [comment] 2024-11-29 18:25
Duplicate of: https://github.com/spring-cloud/spring-cloud-stream/issues/3048

**Closed by artembilan** 2024-11-29 18:25 UTC
