### ISSUE TITLE
Payload is base64-encoded when setting correct contentType

### ISSUE THREAD

**Issue by bikerlad** [spring-cloud/spring-cloud-stream#1180] opened 2018-01-15 12:02 UTC
I'm using Spring Cloud Edgware and Spring Cloud DataFlow 1.2.3.

I'm having problems with setting contentType to the correct value in a specific scenario.

I have various dataflow streams all sinking data to a rabbit sink, 1.3.1.RELEASE of spring-cloud-starter-stream-sink-rabbit (call it datasink for the purposes of this explanation). The rabbit source in play is 1.3.1.RELEASE of spring-cloud-starter-stream-source-rabbit.

The data in the rabbit sink is correctly application/json. The streams producing the data have Processors which munge stuff and explicitly set the output contentType to application/json in the code. This has all been working correctly for over a year and still does.

There is now a need to introduce a bridge between the datasink and another rabbit sink. The new bridge stream is simply:

`rabbit-source | rabbit-sink`

where rabbit-source reads from the aforementioned datasink.

The sinked data in the bridge stubbornly has a contentType of application/octet-stream.

I have tried the following setting:

`app.rabbit-source.spring.cloud.stream.bindings.output.content-type=application/json`

This results in a sinked contentType of application/json. However, the payload is inexplicably base64-encoded!

Following a suggestion from Oleg Zhurakousky, I tried an upgrade to Ditmars.SR3 and used the following setting in the above stream (on each component and both):

`--spring.cloud.stream.default.contentType=application/json`

This results in a contentType of application/json but the payload is still base64-encoded.

(My workaround is to hack the rabbit sink and to programmatically overwrite the contentType header with the originalContentType header if present, which is far from ideal.)

**Comment by olegz** [comment] 2018-01-15 12:33
Linking the original SO thread https://stackoverflow.com/questions/48226744/spring-cloud-dataflow-and-originalcontenttype/48227265#48227265

**Comment by olegz** [comment] 2018-01-23 12:18
@bikerlad I've tried to see if I can reproduce it, but unfortunately I can't, so something else must be going on in your environment.
I had a few hunches, but the fact that you are reporting this issue on 1.3.x line makes me wonder. There was a bug fix to spring-amqp which kind of changed how the headers are mapped and could have potentially cause your issue, but since you are on 1.3 line that would not affect you unless you did some classpath customization

What I also can't understand is the "Base-64 comment". We never had nor we do have any base-64 encoders/decoders, so it must be something custom that you have.

IN any event, the best way forward would be for you to wrap this into some simple application and share it via Github or other means so we can try to reproduce it.

**Comment by olegz** [comment] 2018-01-28 20:10
I am going to close it since there is no feedback. Please feel free to re-open it if you still see it as an issue providing requested information.

**Closed by olegz** 2018-01-28 20:10 UTC
Labels: backport-1.3.x, content-type-improvement, waiting-on-feedback

**Comment by bikerlad** [comment] 2018-01-30 13:07
I'll find some time to investigate further and put together a demo if necessary once I've exhausted all environmental issues.
