### ISSUE TITLE
Spring Cloud Stream Sending Two Schemas to Registry Every Time

### ISSUE THREAD

**Issue by mikeayonguyen** [spring-cloud/spring-cloud-stream#1555] opened 2018-12-13 01:54 UTC
**I'm trying to set up Spring Cloud Stream with Confluent Schema Registry. However, running through the logs, I can see that it's posting two schemas to the registry, into two separate subjects.**

`
10 Dec 2018 ; 09:33:30.830 [main] DEBUG o.s.web.client.RestTemplate - Created POST request for "http://xxxxx.com/subjects/xwalk/versions" 10 Dec 2018 ; 09:33:30.844 [main] DEBUG o.s.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json] 10 Dec 2018 ; 09:33:30.845 [main] DEBUG o.s.web.client.RestTemplate - Writing [{"schema":"{\"type\":\"record\",\"name\":\"Xwalk\",\"namespace\":\"com.xxx.xxx.gr.igp.xwalk.avro\",\"fields\":[{\"name\":\"Crosswalk\",\"type\":{\"type\":\"record\",\"name\":\"Crosswalk\",\"fields\":[{\"name\":\"IndividualIdentifier\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"Identifier\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Identifier\",\"fields\":[{\"name\":\"Source_identifier\",\"type\":{\"type\":\"record\",\"name\":\"Source_identifier\",\"fields\":[{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"last_update_date\",\"type\":\"string\"}]}},{\"name\":\"related_id\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"related_id\",\"fields\":[{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]}]}]}}}]}}]}"}] as "application/json" using [org.springframework.http.converter.StringHttpMessageConverter@514cd540] 10 Dec 2018 ; 09:33:31.070 [main] DEBUG o.s.web.client.RestTemplate - POST request for "http://xxxxx.com/subjects/xwalk/versions" resulted in 200 (OK) 10 Dec 2018 ; 09:33:31.072 [main] DEBUG o.s.web.client.RestTemplate - Reading [interface java.util.Map] as "application/vnd.schemaregistry.v1+json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@6b0615ae] 10 Dec 2018 ; 09:33:31.113 [main] DEBUG o.s.web.client.RestTemplate - Created POST request for "http://xxxxx.com/subjects/xwalk" 10 Dec 2018 ; 09:33:31.114 [main] DEBUG o.s.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json] 10 Dec 2018 ; 09:33:31.114 [main] DEBUG o.s.web.client.RestTemplate - Writing [{"schema":"{\"type\":\"record\",\"name\":\"Xwalk\",\"namespace\":\"com.xxx.xxx
.gr.igp.xwalk.avro\",\"fields\":[{\"name\":\"Crosswalk\",\"type\":{\"type\":\"record\",\"name\":\"Crosswalk\",\"fields\":[{\"name\":\"IndividualIdentifier\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"Identifier\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Identifier\",\"fields\":[{\"name\":\"Source_identifier\",\"type\":{\"type\":\"record\",\"name\":\"Source_identifier\",\"fields\":[{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"last_update_date\",\"type\":\"string\"}]}},{\"name\":\"related_id\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"related_id\",\"fields\":[{\"name\":\"source_system_cd\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]}]}]}}}]}}]}"}] as "application/json" using [org.springframework.http.converter.StringHttpMessageConverter@514cd540] 10 Dec 2018 ; 09:33:31.206 [main] DEBUG o.s.web.client.RestTemplate - POST request for "http://xxxxx.com/subjects/xwalk" resulted in 200 (OK) 10 Dec 2018 ; 09:33:31.206 [main] DEBUG o.s.web.client.RestTemplate - Reading [interface java.util.Map] as "application/vnd.schemaregistry.v1+json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@6b0615ae]
`

**After publishing the Avro message. It makes another POST request to the Confluent Schema Registry. This time saying the schema is bytes.**

`10 Dec 2018 ; 09:35:06.424 [kaas.xxx.stg.gr_publishing_topic.container-0-C-1] DEBUG i.c.k.s.client.rest.RestService - Sending POST with input {"schema":"\"bytes\""} to http://xxxxx.com/subjects/kaas.xxx.stg.xwalk-value/versions`

**These schemas are being published to two separate subjects. The first being 'xwalk', which is the type of the Avro object I'm publishing, and the second being 'kaas.xxx.stg.xwalk-value', which is the topic I'm publishing to. How do I get them both to publish to a single subject, and as a schema and not "bytes"?**

**Comment by olegz** [comment] 2018-12-18 12:22
Can you please provide a reproducible sample or at the very least outline steps to reproduce the issue?

**Comment by mikeayonguyen** [comment] 2018-12-19 15:06
**Hey olegz,**

**I was following the following sample:** https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/schema-registry-samples/schema-registry-confluent

**Here is my configuration file:**
```
spring.cloud.stream.bindings.input.destination=${KAAS_IN:kaas.imdm.stg.gr_publishing_topic}
spring.cloud.stream.bindings.output.destination=${KAAS_OUT:kaas.imdm.stg.xwalk}
spring.cloud.stream.kafka.binder.brokers=xxxxx.com:443
spring.cloud.stream.kafka.binder.defaultBrokerPort=443
spring.cloud.stream.kafka.binder.configuration.security.protocol=SSL
spring.cloud.stream.kafka.binder.configuration.ssl.truststore.location=${TRUSTSTORE_PATH:kaas.client.truststore.jks}
spring.cloud.stream.kafka.binder.configuration.ssl.truststore.password=${TRUSTSTORE_PASSWORD:}
spring.cloud.stream.kafka.binder.configuration.ssl.keystore.location=${KEYSTORE_PATH:imdm-streams.keystore.jks}
spring.cloud.stream.kafka.binder.configuration.ssl.keystore.password=${KEYSTORE_PASSWORD:}
spring.cloud.stream.kafka.binder.configuration.ssl.key.password=${KEY_PASSWORD:}
spring.cloud.stream.kafka.binder.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.binder.configuration.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.cloud.stream.kafka.bindings.output.producer.configuration.schema.registry.url=http://xxxxx.com
spring.cloud.stream.bindings.output.contentType=application/*+avro

spring.cloud.stream.schemaRegistryClient.endpoint=http://xxxxx.com
spring.cloud.stream.schema.avro.schema-locations=classpath:avro/crosswalk-value.avsc

spring.profiles.active=secrets

management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
```

**And here is my producer:**
```
@SpringBootApplication
@EnableBinding(Processor.class)
@EnableSchemaRegistryClient
public class EnterpriseGrApplication {

	private static final Logger logger = LoggerFactory.getLogger(EnterpriseGrApplication.class);

	@Autowired
	private Processor processor;

	private static int recordCount = 1;

	public static void main(String[] args) {
		SpringApplication.run(EnterpriseGrApplication.class, args);
	}

	@StreamListener(Processor.INPUT)
	public void handle(String GRXMLString) throws JsonParseException, JsonMappingException, IOException {

		logger.info("Record #{} received.", recordCount);

		Xwalk xWalkJSON = XwalkConverter.toXwalk(GRXMLString);

		if (xWalkJSON != null) {
			processor.output().send(message(xWalkJSON));
		}

		recordCount++;
	}

	private static final <T> Message<T> message(T val) {
		return MessageBuilder.withPayload(val).build();
	}

	@Configuration
	static class ConfluentSchemaRegistryConfiguration {
		@Bean
		public SchemaRegistryClient schemaRegistryClient(
				@Value("${spring.cloud.stream.schemaRegistryClient.endpoint}") String endpoint) {
			ConfluentSchemaRegistryClient client = new ConfluentSchemaRegistryClient();
			client.setEndpoint(endpoint);
			return client;
		}
	}
}
```

**The method XwalkConverter.toXwalk returns an Avro message using the class generated from the following plugin:**
```
                         <plugin>
				<groupId>org.apache.avro</groupId>
				<artifactId>avro-maven-plugin</artifactId>
				<version>1.8.2</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>schema</goal>
							<goal>protocol</goal>
							<goal>idl-protocol</goal>
						</goals>
						<configuration>
							<sourceDirectory>src/main/resources/avro</sourceDirectory>
							<outputDirectory>src/main/java</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by mikeayonguyen** [comment] 2018-12-27 16:57
I even setup my own Confluent Schema Registry and it's posting as "bytes".

`$ curl -X GET http://localhost:8081/subjects/kaas.imdm.stg.xwalk-value/versions/1
{"subject":"kaas.imdm.stg.xwalk-value","version":1,"id":2,"schema":"\"bytes\""}`

**Comment by sobychacko** [comment] 2019-01-08 20:16
@mikeayonguyen I tried to run the sample [here](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/schema-registry-samples/schema-registry-confluent), but I am unable to reproduce the behavior that you are seeing, i.e. a second schema as bytes. What is `i.c.k.s.client.rest.RestService` in your log? I don't think Spring Cloud Stream stack goes through that class. Can you see if you can reproduce the issue using the sample and provide a link to your fork? Or provide a small sample app altogether in which it is reproduced. That way, we can further assist you.

**Comment by mikeayonguyen** [comment] 2019-01-08 20:18
How was the subject posted for the sample that you ran? When I ran it, the
subject was "sensor" and not the usual behavior of "<topic>-value".

**Comment by sobychacko** [comment] 2019-01-10 20:07
@mikeayonguyen Any update to this issue?

**Comment by olegz** [comment] 2019-01-22 15:24
@mikeayonguyen please respond to @sobychacko otherwise since we can't reproduce the issue it will be closed. Feel free to close it yourself if you believe it's no longer an issue

**Comment by olegz** [comment] 2019-05-17 14:21
I am closing this due to inactivity from the original reporter

**Closed by olegz** 2019-05-17 14:21 UTC
Labels: question, waiting-on-feedback
