### ISSUE TITLE
Integration tests for streams

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-stream#1001] opened 2017-06-27 12:09 UTC
Hi ! 

I'd like to test a basic stream like this : 
``` 
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = {TimeSourceApplication.class, ProcessorApplication.class, LogSinkApplication.class})
@EnableSmartstreamRegistryServer
@DirtiesContext
public class StreamTest {

    final static Logger LOG = LoggerFactory.getLogger(StreamTest.class);

    @Autowired
    protected Source source;

    @Autowired
    protected Processor processor;

    @Autowired
    protected Sink sink;

    @Autowired
    protected MessageCollector collector;

    @Test
    public void test() throws InterruptedException, IOException {
        Thread.sleep(2000);

        System.out.println("########################### TEST START ##############################");
        BlockingQueue<Message<?>> queue = collector.forChannel(source.output());

        for (int i = 0; i < 10000; i++) {
            Message<?> element = queue.poll(1, TimeUnit.SECONDS);
            if(element != null) {
                Object txn = element.getPayload();
                System.out.println(txn.toString());
            }
        }
        System.out.println("########################### TEST   END ##############################");
    }
}


``` 

But I get this kind of errors : 
``` 
java.lang.IllegalStateException: Failed to load ApplicationContext

Caused by: org.springframework.beans.factory.BeanInitializationException: Duplicate @StreamListener mapping for 'input' on sink.log.LogSink#doReceive[1 args] already existing for processor.log.LogProcessor#doProcess[1 args]

``` 

I was wondering if there was any solution to load my Sink, Source and Processor with "independent" Application Context, in order to test the result coming of the sink ouput , test the "average" speed of my stream and other stuff...

**Comment by mbogoevici** [comment] 2017-07-11 21:31
Duplicate of #592

**Closed by mbogoevici** 2017-07-11 21:31 UTC
Labels: documentation, duplicate, question
