### ISSUE TITLE
StreamInputDestinationMessageSender is getting the destination from the definition which is wrong property key

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream#2134] opened 2021-01-25 09:56 UTC
**Describe the bug**
I am upgrading to the new spring cloud stream functional way of doing things (Hoxton.SR9) and using the new test binder.  When invoking my producer contract StreamInputDestinationMessageSender seems to be reading the destination from the definition field which is wrong. I think it should be looking up destination from the property config

**Sample**
I have a producer contract as follows
```
Contract.make {
    description('should send an exchange times event on a scheduled event')

    label('triggerExchangeTimesEventOnScheduledEvent')
    input {
        triggeredBy('triggerExchangeTimesEventOnScheduledEvent()')
    }
    outputMessage {
        sentTo('exchange-times-events')
```
where 'exchange-times-events' is my Kafka topic.  

In my consumer I have a simple function

```
 @Bean
  public Consumer<Flux<ExchangeTimeEvent>> exchangeTimes() {
    return events -> events.subscribe(event -> {
      log.info("exchangeTimeEvent = {}", event);
      ....
    });
  }
```
and properties
```
spring.cloud.stream.bindings.exchangeTimes-in-0.destination=exchange-times-events
spring.cloud.function.definition=exchangeTimes
```

 To test this I am using the new  new streams test binder and invoking my contract as such.
```
  @Test
  public void shouldGetTheExchange() {
    stubTrigger.trigger("triggerExchangeTimesEventOnScheduledEvent");
```
and I get the error "Destination with name [exchange-times-events] not found in the function definitions [exchangeTimes]"

because org.springframework.cloud.contract.verifier.messaging.stream.StreamInputDestinationMessageSender indexOfDestination is looking for the destination in the definition which I don't think is right.  The destination must be looked up from the definition surely? I would of thought StreamInputDestinationMessageSender gets the definition then looks up spring.cloud.stream.bindings.{definition}-in-0.destination to get the destination?

Is this a bug?  

Thanks

**Comment by marcingrzejszczak** [comment] 2021-03-10 13:02
I've transferred the issue to Spring Cloud Stream since the issue is related to mixing binding specific features with core features (in this case `use-native-decoding=true`). @olegz will provide more details.

**Comment by olegz** [comment] 2021-03-10 13:26
So, Marcin and I just went thru a debug session and there is really nothing to fix on either stream or contract side other than  possibly provide a more user friendly error message and that is what I'll do.

But here are the details . . .
The Test Binder is meant to emulate core features of spring-cloud-stream and binders that support those features. It is not meant to emulate binder specific features like native encoding/decoding that is supported only by Kafka binder. So in this case the native decoding was set resulting in s-c-stream performing no-input conversion assuming something else would (which would happen in the case of Kafka binder), but nothing did resulting in CCException.

I will keep this issue open and see if we can add a more descriptive error message

**Comment by davidmelia** [comment] 2021-03-10 14:51
@olegz  @marcingrzejszczak 

Couple of observations in my prototype

**if I turn off native decoding it has no effect**
`spring.cloud.stream.bindings.consumeAvro-in-0.consumer.use-native-decoding=false`
it fails

**If I update to spring cloud 2020.0.1 and boot 2.4.3 and turn off native binding it works.**

does this suggest in order to take advantage of spring cloud stream functional way I need to upgrade??

Thanks

**Comment by olegz** [comment] 2021-03-10 14:54
No, stream 3.0.x (Hoxton/Horsham) is functional. When you say `if I turn off native decoding it has no effect` what do you mean by that? Any exception?

**Comment by davidmelia** [comment] 2021-03-10 18:19
@olegz I have updated https://github.com/davidmelia/spring-cloud-contract-producer-kafka-consumer and set 
`spring.cloud.stream.bindings.consumeAvro-in-0.consumer.use-native-decoding=false`

and I still get the error

`Destination with name [avro-fx-rate-events] not found in the function definitions [consumeAvro;consumeJson]`

I think there is definitely a bug here somewhere.

Upgrading to cloud 2020.0.1 and boot 2.4.3 the problem seems to be fixed and my tests pass.

**Comment by olegz** [comment] 2021-05-25 10:56
I guess I would need some way of reproducing it. Perhaps a small project that you can push somewhere on guthub.
Given the age of this issue and the fact that you have confirmed that it works on 3.1, i'll close it, but feel free to reopen it or raise a fresh one if you provide a way of reproducing it.

**Closed by olegz** 2021-05-25 10:56 UTC
Labels: Backport Horsham, documentation, task
