### ISSUE TITLE
Defining Name for Spring Cloud Stream Binding in Actuator Endpoint

### ISSUE THREAD

**Issue by azizabah** [spring-cloud/spring-cloud-stream#1476] opened 2018-09-14 20:14 UTC
When using Spring Cloud Stream with RabbitMQ, it allows you to expose the /bindings actuator which provides great information about the bindings. It also exposes the /bindings/{name} endpoint to allow you to modify the state of a running binding.

Unfortunately, if you are binding multiple listeners to the same exchange, they end up getting the same name. This is with a configuration that looks like this
```
spring.cloud.stream.bindings.data-available.destination=data.topic.exchange
spring.cloud.stream.bindings.data-available.group=data.copydata.queue.mirror
spring.cloud.stream.bindings.data-available.consumer.back-off-initial-interval=2000
spring.cloud.stream.rabbit.bindings.data-available.consumer.queueNameGroupOnly=true
spring.cloud.stream.rabbit.bindings.data-available.consumer.bindingRoutingKey=data-ready
```
So if I hit localhost:8080/actuator/bindings/ I see that there is a binding named "data.topic.exchange". Is there any way to change that name or to set it to something else such as "data-available" which is the name of the binding for all other intents and purposes such as defining it in the binding bean inside my application.

Coming from this [SO issue](https://stackoverflow.com/questions/52338379/defining-name-for-spring-cloud-stream-binding-in-actuator-endpoint)

**Comment by olegz** [comment] 2018-09-16 15:46
As explained in the [SO Issue](https://stackoverflow.com/questions/52338379/defining-name-for-spring-cloud-stream-binding-in-actuator-endpoint), this is not a bug. We simply do not provide this feature at the moment.

**Comment by azizabah** [comment] 2018-09-17 13:04
@olegz  - That's fair. Here's where my confusion over the behavior is coming from: If I go to /bindings, then I can see all of my listeners. However it is **impossible** to access any of them except for the first through the exposed /bindings/{name} behavior. I would consider that a bug because of the inconsistent behavior between the two parts of the actuator. 

Having said that, if a feature request works better for you folks, I am fine with that. Here's how I think it would much more helpful to work like:
Either my thought above on using the binder name or perhaps having the name in the actuator be destination.group regardless of the setting of the queue-name-group-only property would be preferred behavior. Either of those should allow you to access all of your bindings from the actuator.

**Comment by olegz** [comment] 2019-01-22 07:52
Resolved with https://github.com/olegz/spring-cloud-stream/commit/144627c4355b51b81ace7c4254e3a8b68ba21a3d

**Closed by olegz** 2019-01-22 07:52 UTC
Labels: enhancement
