### ISSUE TITLE
JSON array cannot be cast to POJO list

### ISSUE THREAD

**Issue by shishuwu** [spring-cloud/spring-cloud-stream#726] opened 2016-12-01 01:03 UTC
I'm doing some tests of the **content type auto-conversion** of Spring Cloud Stream. 

As the [spring-cloud-stream Guide](http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#__literal_streamlistener_literal_and_message_conversion) shows. The json format of `GreetingMessage `(`{"greeting":"Hello, world"}`) will be cast to **POJO** `GreetingMessage ` object automatically when consumes in the `@StreamListener`. This tests successfully.

**But**, when i change the *output* as `List<GreetingMessage > [{"greeting":"Hello, world"}, {"greeting":"Good morning"}]`, the *input* **WILL NOT** cast it to **POJO** `List<GreetingMessage >` objects, but as **POJO** `List<String>`.

More detail, please refer to my [question](http://stackoverflow.com/questions/40893440/spring-cloud-stream-json-array-cannot-be-cast-to-pojo-list) from stackoverflow.

**Comment by mbogoevici** [comment] 2016-12-01 03:01
Thank you @shishuwu for opening the issue. 

At a first glance I believe that this is caused by the `PayloadArgumentResolver` coming from Spring itself (i.e. here https://github.com/spring-projects/spring-framework/blob/4.3.x/spring-messaging/src/main/java/org/springframework/messaging/handler/annotation/support/PayloadArgumentResolver.java#L126)  - which is used by the StreamListener under the scenes, but we should take a deeper look at this.

**Comment by mbogoevici** [comment] 2017-07-11 19:35
Needs filing an issue against Spring Framework or provide a custom PayloadArgumentResolver.

**Comment by mbogoevici** [comment] 2017-07-18 00:31
Deferring to a later version as this requires changes not only to the `PayloadArgumentResolver` but also to the way in which the `MessageConverter` implementation operates.

**Comment by olegz** [comment] 2018-02-23 12:51
I believe this is already been addressed via other issue, so will close it now, but feel free to re-open it

**Closed by olegz** 2018-02-23 12:51 UTC

**Comment by alecl** [comment] 2019-04-22 19:56
@olegz What issue were you referring to that addressed this? Thanks.

**Comment by jschabowsky** [comment] 2020-04-08 16:24
@olegz @mbogoevici  we are I think having the same problem. If I have a suppler that provides an Object that either: 
1) extends ArrayList (public class POJO extends ArrayList<Items>)
2) Supplier<List<Items>>
3) Supplier<Items[]>
with content-type set to application/json 
What goes across the wire is a JSON array of payloads and headers. Our only work around so far is to do a Supplier<String> and on the return do a objectMapper.writeValueAsString(obj) which seems  incorrect.

Upon input, to a Consumer, it works with either of the three options. I believe it is related to this issue, but could not track further. Pls advise.

**Comment by olegz** [comment] 2020-04-08 17:37
@jschabowsky please do not comment on closed issue. It's closed.
Especially the ~4 year old issue. . .. The version of the framework it was open against is no longer supported. There is nothing to do do here.

If you have an issue, please raise a new one, provide enough details to reproduce it or a code sample, version of the framework you are using etc.
