### ISSUE TITLE
PartitionAwareFunctionWrapper can't work in concurrency >1

### ISSUE THREAD

**Issue by nicolas-zheng** [spring-cloud/spring-cloud-stream#2412] opened 2022-05-30 09:42 UTC
Spring Boot 2.6.6 and Spring Cloud 2021.0.1

sending a partitioned message with a function input=message output=message

there are some messages miss the partition assignment as other threads may set the Enhancer to null. Thanks!

	public Object apply(Object input) {
		this.setEnhancerIfNecessary();
		return this.function.apply(input);
		Object result = this.function.apply(input);
		if (!((FunctionInvocationWrapper) this.function).isInputTypePublisher()) {
			**((FunctionInvocationWrapper) this.function).setEnhancer(null);**
		}
		return result;
	}

**Comment by XIAOANAndy** [comment] 2022-06-06 05:37
I meet the same issue related to PartitionAwareFunctionWrapper , when using streamBridge to send partition and non-partition message in multiple threads.
Thread 1 try to send **non-partition** message
Thread 2 try to send **partition** message
Thread 2 set the enhancer to partitionAwareFunctionWrapper
When Thread 1 try to execute the function, it checks the enhancer is not null and try get the partition key will get the error
StreamBridge.send(...)
![image](https://user-images.githubusercontent.com/47747616/172100680-0ccde7f0-1ec6-42b9-acb4-cdaedc5041dc.png)


SimpleFunctionRegistry.convertOutputIfNecessary(...)
![image](https://user-images.githubusercontent.com/47747616/172100904-9fb3ee76-517e-4abc-b516-ea195afa8640.png)

Error
![image](https://user-images.githubusercontent.com/47747616/172101242-d7c7a2b5-bddc-4756-bb3c-15f2b1265e58.png)

**Comment by nicolas-zheng** [comment] 2022-06-07 03:28
it is fixed in spring cloud stream version 3.2.4 or <spring-cloud.version>2021.0.3</spring-cloud.version>

**Comment by olegz** [comment] 2022-06-09 13:30
Can you please provide a small sample that would reproduce the issue. Basically a small project that  we can clone and test

**Comment by nicolas-zheng** [comment] 2022-06-22 05:57
found this fixed in StreamBridge but didn't cover sending message by function.

https://github.com/spring-cloud/spring-cloud-stream/commit/f58dcf371db7cadb9ddf9de9ef018fa575ec10fd

**Comment by pongpongcn** [comment] 2022-09-07 10:25
I have the same problem.

Here is a test project using function.

[testconsumerconcurrency.zip](https://github.com/spring-cloud/spring-cloud-stream/files/9505165/testconsumerconcurrency.zip)

@olegz 

Just execute
```shell
mvn spring-boot:run
```

Messages(MyEvent) with same partition key would not be in same partition of test-response queue.

| Partition | Size | 
|-----------|------| 
| 0         | 59   | 
| 1         | 73   | 
| 2         | 809  | 
| 3         | 59   | 

My quick fix

```java
public Object apply(Object input) {
    Object result;
    synchronized (this.function)
    {
        this.setEnhancerIfNecessary();
        result = this.function.apply(input);
        if (!((FunctionInvocationWrapper) this.function).isInputTypePublisher()) {
            ((FunctionInvocationWrapper) this.function).setEnhancer(null);
        }
    }
    return result;
}
```

**Comment by sobychacko** [comment] 2023-09-13 21:04
@pongpongcn Is this still an issue for you? There have been a lot of code changes in this area since the last time you updated on the issue. If it works, can we close the issue? If you are still facing the issue, please ping us here, and we will look at this soon.

**Comment by sobychacko** [comment] 2023-10-19 13:47
Closing the issue due to no activity. Feel free to re-open if there is a need.

**Closed by sobychacko** 2023-10-19 13:47 UTC
Labels: waiting-on-feedback
