### ISSUE TITLE
Spike: Add `@ProducerListener` at core level

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#917] opened 2017-04-11 19:00 UTC
- wherever the underlying messaging client supports asynchronous notifications - or support returns and confirms for Rabbit
- might be also invocable synchronously from the producer?

**Comment by sabbyanandan** [comment] 2017-06-22 17:01
Duplicate of #916.

**Closed by sabbyanandan** 2017-06-22 17:01 UTC
Labels: duplicate, spike
