### ISSUE TITLE
StreamListener adapters trigger early instantiation cascade

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1146] opened 2017-11-27 09:57 UTC
I think the main culprit is not `StreamListenerAnnotationBeanPostProcessor`, but rather the things it depends on, since it does `BeanFactoryUtils.beansOfTypeIncludingAncestors()` a lot and those beans don't do lazy lookups when they could. But one or the other probably needs to change to prevent a mess of early instantiation, e.g.

```
2017-11-27 18:37:03.242  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration' of type [org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration$$EnhancerBySpringCGLIB$$a3a08db8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.295  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.304  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.326  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration' of type [org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration$$EnhancerBySpringCGLIB$$9efc6d8f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.417  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$$EnhancerBySpringCGLIB$$dd71277f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.424  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spelConverter' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$SpelConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.427  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.function.stream-org.springframework.cloud.function.stream.config.StreamConfigurationProperties' of type [org.springframework.cloud.function.stream.config.StreamConfigurationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.428  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.function.stream.config.StreamAutoConfiguration' of type [org.springframework.cloud.function.stream.config.StreamAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.433  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.reactive.ReactiveSupportAutoConfiguration' of type [org.springframework.cloud.stream.reactive.ReactiveSupportAutoConfiguration$$EnhancerBySpringCGLIB$$251631e7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.440  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelToFluxSenderArgumentAdapter' of type [org.springframework.cloud.stream.reactive.MessageChannelToFluxSenderParameterAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.442  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelToFunctionInvokerParameterAdapter' of type [org.springframework.cloud.function.stream.config.MessageChannelToFunctionInvokerParameterAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.448  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration$$EnhancerBySpringCGLIB$$38c84f1b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.455  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.jackson-org.springframework.boot.autoconfigure.jackson.JacksonProperties' of type [org.springframework.boot.autoconfigure.jackson.JacksonProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.459  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration$$EnhancerBySpringCGLIB$$a62bf723] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.465  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'standardJacksonObjectMapperBuilderCustomizer' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration$StandardJackson2ObjectMapperBuilderCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.467  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration$$EnhancerBySpringCGLIB$$eb151134] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.473  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$$EnhancerBySpringCGLIB$$1ad3ecaa] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.496  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jsonComponentModule' of type [org.springframework.boot.jackson.JsonComponentModule] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.500  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jacksonObjectMapperBuilder' of type [org.springframework.http.converter.json.Jackson2ObjectMapperBuilder] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.518  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jacksonObjectMapper' of type [com.fasterxml.jackson.databind.ObjectMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.532  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationConversionService' of type [org.springframework.integration.context.CustomConversionServiceFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.532  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationConversionService' of type [org.springframework.core.convert.support.DefaultConversionService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.533  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'datatypeChannelMessageConverter' of type [org.springframework.integration.support.converter.DefaultDatatypeChannelMessageConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.533  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.BindingServiceConfiguration' of type [org.springframework.cloud.stream.config.BindingServiceConfiguration$$EnhancerBySpringCGLIB$$33661d7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.543  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'compositeMessageConverterFactory' of type [org.springframework.cloud.stream.converter.CompositeMessageConverterFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.546  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelToInputFluxArgumentAdapter' of type [org.springframework.cloud.stream.reactive.MessageChannelToInputFluxParameterAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-27 18:37:03.550  INFO 32380 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'fluxToMessageChannelResultAdapter' of type [org.springframework.cloud.stream.reactive.FluxToMessageChannelResultAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

Some of those come from Spring Integration core, and maybe won't be harmful. We could maybe look at reducing the Stream induced ones.

**Comment by olegz** [comment] 2017-11-27 12:58
@dsyer I've noticed that as well while working on unrelated issue. . . There are other places as well where we do similar things. I have a few ideas, let me work'em.

**Comment by olegz** [comment] 2017-11-27 17:12
So, it appears that one of the issue is more general where any `@Configuration` class that defines at least one BPPs will trigger this message unless itself is annotated with `@Role(BeanDefinition.ROLE_INFRASTRUCTURE)` - (which they probably should be)

**Comment by dsyer** [comment] 2017-11-28 12:21
`SLABPP` is doing some really evil things though. I noticed some changes in master, so it might be improving, but in 1.3.x it actually does bean lookups by type in its own `afterPropertiesSet()` (so all beans of those types and all their dependencies are eagerly instantiated). It's kind of a disaster to do that. IMO all this processing should be deferred to after the context is refreshed (or maybe in a `SmartLifecycle` if it needs to be earlier).

**Comment by olegz** [comment] 2017-11-28 12:42
Indeed! And that is gone. I mean the whole `afterPropertiesSet()` and yes, there is more cleaning under way

**Comment by dsyer** [comment] 2017-11-28 12:53
Any chance of a back port? Some people are going to be using Ditmars for a long time.

**Comment by olegz** [comment] 2017-11-28 12:56
Yeah, that is one of the reasons why I am pushing back on 1.3.1, so we can potentially include things like this

**Comment by olegz** [comment] 2017-11-28 13:43
@dsyer it's been back ported (see https://github.com/spring-cloud/spring-cloud-stream/commit/dad81c617baf1935e4c5b731fa72e10875fcf0c3).  But I am sure as the work continues there will be more

**Comment by dsyer** [comment] 2017-11-30 10:20
I don't think this is fixed by quite a long chalk, so I'll re-open while we do some more digging

```
2017-11-30 10:18:47.800  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.803  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'integrationGlobalProperties' of type [java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.826  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration' of type [org.springframework.cloud.stream.config.BindingServiceConfiguration$PostProcessorConfiguration$$EnhancerBySpringCGLIB$$2aef9361] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.905  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'spelConverter' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$SpelConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.909  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.stream.integration-org.springframework.cloud.stream.config.SpringIntegrationProperties' of type [org.springframework.cloud.stream.config.SpringIntegrationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.921  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.function.web.flux.ReactorAutoConfiguration' of type [org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$$EnhancerBySpringCGLIB$$1ead79bb] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.930  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.stream.reactive.ReactiveSupportAutoConfiguration' of type [org.springframework.cloud.stream.reactive.ReactiveSupportAutoConfiguration$$EnhancerBySpringCGLIB$$b10957b9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.936  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration$$EnhancerBySpringCGLIB$$c4bb74ed] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.940  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration$$EnhancerBySpringCGLIB$$77083706] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.944  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration$$EnhancerBySpringCGLIB$$321f1cf5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.949  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'spring.jackson-org.springframework.boot.autoconfigure.jackson.JacksonProperties' of type [org.springframework.boot.autoconfigure.jackson.JacksonProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.953  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'standardJacksonObjectMapperBuilderCustomizer' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration$StandardJackson2ObjectMapperBuilderCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.957  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration' of type [org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$$EnhancerBySpringCGLIB$$a6c7127c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.978  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'jsonComponentModule' of type [org.springframework.boot.jackson.JsonComponentModule] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.980  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'jacksonObjectMapperBuilder' of type [org.springframework.http.converter.json.Jackson2ObjectMapperBuilder] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:47.997  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'jacksonObjectMapper' of type [com.fasterxml.jackson.databind.ObjectMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.004  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'integrationConversionService' of type [org.springframework.integration.context.CustomConversionServiceFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.004  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'integrationConversionService' of type [org.springframework.core.convert.support.DefaultConversionService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.004  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'datatypeChannelMessageConverter' of type [org.springframework.integration.support.converter.DefaultDatatypeChannelMessageConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.013  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'compositeMessageConverterFactory' of type [org.springframework.cloud.stream.converter.CompositeMessageConverterFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.016  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelToInputFluxArgumentAdapter' of type [org.springframework.cloud.stream.reactive.MessageChannelToInputFluxParameterAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.018  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelToFluxSenderArgumentAdapter' of type [org.springframework.cloud.stream.reactive.MessageChannelToFluxSenderParameterAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-30 10:18:48.021  INFO 10128 --- [       Thread-1] trationDelegate$BeanPostProcessorChecker : Bean 'messageChannelStreamListenerResultAdapter' of type [org.springframework.cloud.stream.binding.MessageChannelStreamListenerResultAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**Comment by olegz** [comment] 2017-11-30 12:00
@dsyer perhaps renaming it to something more general then? While there are few minor things related to this may still need to be addressed in StreamListener, the vast majority is outside of it, so we need a more generic description.

**Comment by dsyer** [comment] 2017-12-01 09:47
It's not a general problem, it's a set of specific problems tied to individual BPP implementations. I don't think it's minor in `StreamListenerAnnotationBeanPostProcessor`, I think it will require some surgery, so let's fix that, resolve this issue and then move on. `StreamListenerAnnotationBeanPostProcessor` might need to inspect every bean as it is created, looking for the annotatipm, but we really need to see if it can defer the processing (and looking up its dependencies) until the `BeanFactory` is ready.

**Comment by dsyer** [comment] 2017-12-01 11:03
Lots of bean post processors here as well: `BindingServiceConfiguration.PostProcessorConfiguration`. Similar issues.

**Comment by olegz** [comment] 2017-12-01 11:40
That is what I was trying to say. It's scattered across the code base, so I'll change the name of this issue to something more descriptive

**Closed** 2017-12-13 16:15 UTC
Labels: backport-1.3.x

**Comment by olegz** [comment] 2017-12-13 16:18
@dsyer the last commit resolves the issue by removing all autowiring from SLBPP. 
There are still work to be done elsewhere, but this one now behaves properly (although I plan to polish it even more).
Please let me know if you feel differently.

**Comment by dsyer** [comment] 2017-12-14 09:45
Are we backporting that latest change (I don't see any improvement with Edgware.BUILD-SNAPSHOT)?

**Comment by olegz** [comment] 2017-12-14 15:02
@dsyer no it hasn't been but I'll work on back-porting it shortly

**Comment by olegz** [comment] 2017-12-15 15:53
@dsyer the latest changes have been back-ported.

**Comment by dsyer** [comment] 2017-12-15 18:03
No change here that I can see. All those `BeanPostProcessorChecker` messages still show up on startup, even though the `StreamListenerAnnotationBeanPostProcessor` has moved it's depdendency lookup till later in the cycle (`afterSingletonsInstantiated()` which is pretty early still).

**Comment by olegz** [comment] 2017-12-15 18:15
Hmm, 
I don't think you see anything coming out of or triggered by SLABPP.
There are indeed other components that still need work, and I am taking care of them incrementally one at the time.
Also, not sure I fully understand how is `afterSingletonsInstantiated` is _pretty early still_? Wasn't the whole purpose of it to address this exact issue? Am I missing something?

**Comment by dsyer** [comment] 2017-12-18 09:21
`StreamEmitterAnnotationBeanPostProcessor` is one culprit in this project. The same anti-pattern.

I guess `afterSingletonsInstantiated()` might turn out to be a good choice. I haven't tried that before in similar situations.

**Comment by olegz** [comment] 2017-12-18 20:16
Agreed and is one I am working on to introduce same changes.

As for 'afterSingletonsInstantiated()' after discussing it with few folks and stepping through the code I believe we're ok as it is executed way past BPP lifecycle.
