### ISSUE TITLE
Output destination test binder does not receive message after Spring Boot 3.2.7

### ISSUE THREAD

**Issue by nateha1984** [spring-cloud/spring-cloud-stream#2996] opened 2024-08-29 15:39 UTC
**Describe the issue**
When using Spring Cloud Stream test binders to test that a message was sent, no message is received from the test binder. A NullPointerError is produce when attempting to receive the message:

java.lang.NullPointerException: Cannot invoke "org.springframework.messaging.Message.getPayload()" because the return value of "org.springframework.cloud.stream.binder.test.OutputDestination.receive()" is null

This works fine in 3.2.7, but upgrading to 3.2.8 or 3.3.x causes this behavior. Project with issue: https://github.com/nateha1984/spring-cloud-test-binder-question

Has something changed with the test configuration? I can't find anything looking through release notes or documentation but am willing to try other test configurations.

**To Reproduce**
1. Clone project from https://github.com/nateha1984/spring-cloud-test-binder-question
2. run mvn clean test, notice that the build completes
3. Upgrade spring boot parent in the pom to 3.2.8+
4. run mvn clean test, see test failures with error

**Version of the framework** 
Spring Boot 3.2.8+, Spring Cloud 2023.0.3
**Expected behavior**
Tests pass and message is received by OutputDestination

**Comment by Tom73525** [comment] 2024-09-03 03:23
I'm able to replicate the same issue. Using a consumer function in my case and no message is being received.

Using Spring Boot 3.3.3 and Spring Cloud 20203.0.3

Here's my stacktrace:

`
2024-09-02T22:51:58.410-04:00 ERROR 19908 --- [app] [container-0-C-1] [                                                 ] o.s.kafka.listener.DefaultErrorHandler   : Backoff none exhausted for status-0@38

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2921)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2862)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2826)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$56(KafkaMessageListenerContainer.java:2744)
    at io.micrometer.observation.Observation.observe(Observation.java:565)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2742)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2595)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2481)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2123)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1478)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1442)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1313)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.springframework.kafka.KafkaException: Failed to execute runnable
    at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.doWithRetry(KafkaInboundEndpoint.java:82)
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:457)
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:422)
    at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2848)
    ... 12 common frames omitted
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@425701fc]
    at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
    at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:108)
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
    at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:132)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
    at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:378)
    at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:349)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:329)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:302)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
    at org.springframework.integration.endpoint.MessageProducerSupport.lambda$sendMessage$1(MessageProducerSupport.java:262)
    at io.micrometer.observation.Observation.observe(Observation.java:499)
    at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:262)
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:391)
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.lambda$onMessage$0(KafkaMessageDrivenChannelAdapter.java:460)
    at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.lambda$doWithRetry$0(KafkaInboundEndpoint.java:77)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:335)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:227)
    at org.springframework.integration.kafka.inbound.KafkaInboundEndpoint.doWithRetry(KafkaInboundEndpoint.java:70)
    ... 15 common frames omitted
Caused by: java.lang.ClassCastException: class [B cannot be cast to class com.myproject.app.utils.MyEventMessage ([B is in module java.base of loader 'bootstrap'; com.myproject.app.utils.MyEventMessage is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @6000fc16)
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:1063)
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:761)
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:592)
    at org.springframework.cloud.stream.function.PartitionAwareFunctionWrapper.apply(PartitionAwareFunctionWrapper.java:92)
    at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionWrapper.apply(FunctionConfiguration.java:823)
    at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:654)
    at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
    ... 37 common frames omitted`

**Comment by Tom73525** [comment] 2024-09-03 03:52
Update: Spring Boot 3.3.3 + Spring Cloud 2023..0.[0 to 2] works fine with receiving messages over consumer functions

**Comment by olegz** [comment] 2024-09-03 06:15
Also, please look at this issue - https://github.com/spring-cloud/spring-cloud-stream/issues/2988.
There was a change in Spring Integration that you have to upgrade manually

**Comment by nateha1984** [comment] 2024-09-03 14:04
Thanks @olegz  it looks like the issue is indeed resolved in 4.1.4-SNAPSHOT

Unfortunately I am not seeing the same results as @Tom73525 on Boot 3.3.3 + Cloud 2023.0.2, that is still failing with a null message here.

**Comment by olegz** [comment] 2024-09-03 14:22
As I said, you should upgrade Spring Integration manually to the latest release

**Comment by olegz** [comment] 2024-09-05 14:20
I am going to close this issue as it has been already reported and resolved

**Closed by olegz** 2024-09-05 14:20 UTC
Labels: waiting-on-feedback
