### ISSUE TITLE
RetryListener not bound to consumer's RetryTemplate in Spring Cloud Stream functional model

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-stream#2853] opened 2023-11-18 21:52 UTC
Please see [this stackoverflow](https://stackoverflow.com/questions/77489337/retrylistener-not-bound-to-consumers-retrytemplate-in-spring-cloud-stream-funct) for a description of this bug. In a response to this stackoverflow, @olegz requested that I open up an issue to address this.

**Comment by sobychacko** [comment] 2023-11-20 23:26
@kabennett Could you create a small sample application where the issue is reproduced with the functional model?

**Comment by sobychacko** [comment] 2024-02-21 21:59
@kabennett Any updates?

**Comment by olegz** [comment] 2024-12-19 11:58
Closing due to lack of follow up from the original reporter

**Closed by olegz** 2024-12-19 11:58 UTC
Labels: enhancement
