### ISSUE TITLE
Injecting interface with MessageChannel fails

### ISSUE THREAD

**Issue by solidgains** [spring-cloud/spring-cloud-stream#574] opened 2016-06-15 05:30 UTC
We used the basic example from here [spring cloud stream reference](http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/) to create a spring boot app that simply puts a message onto a kafka cluster.

We decide to add this simple spring boot app, we can call it "kafka message handler .jar" into another spring boot web application. Now, when we try to inject the service class from our kafka handler jar, (it is annotated with @Service and has a handler method that sends the message), the autowiring fails. The point of failure of the autowiring points to the interface that  has the MessageChannel field. 

In the spring-cloud-stream docs, it states that some implementations of interfaces are generated. It does not seem like this generation step is happening, which is why we get the NoSuchBeanDefinition error. Again, our kafka handler app works fine when we do a Spring Boot run in STS. It's only when we decide to add it as a .jar to another spring boot app that we get the error when injecting the handler class. The kafka handler dependency is being component scanned. I will give exact code tomorrow.

**Comment by mbogoevici** [comment] 2016-06-15 12:47
`@EnableBinding` should be used on a configuration class and not a bean.

A similar question (with more detail) has been asked here: http://stackoverflow.com/questions/37826015/no-qualifying-bean-of-type-com-comcast-activation-message-interfaces-messagecha/37835873#37835873

**Comment by solidgains** [comment] 2016-06-15 15:01
That is my team mate, and our question is the same. 
This is our config in our main class in the parent app. @SpringBootApplication
```
@EnableAsync
@EnableCircuitBreaker
//@RefreshScope
//@Import(ActivatorWebRedisConfig.class)
//@Import(SpringCloudStreamClient.class)
@ComponentScan({"com.comcast.sparrow", "com.comcast.activation.rabittmq", "com.comcast.activation.message"})
```

Some things I did: I removed the @Service that was sitting on top of @EnableBinding since it has @Configuration in it. When I added the @Import(SpringCloudStreamClient.class) in the parent, it complained it was not annotated with @Configuration. So I commented it out. 

However, now what happens is that SpringCloudStreamClient cannot be injected into the controller, it does not go as far as to say MessageChannels cannot be injected into SpringCloudStreamClient.

Maybe this is actually a step back, not forward.

**Comment by mbogoevici** [comment] 2016-06-15 15:04
>  When I added the @Import(SpringCloudStreamClient.class) in the parent, it complained it was not annotated with @Configuration. So I commented it out. 

Is it still annotated with `@EnableBinding()` ? Because `@EnableBinding()` is meta-annotated with `@Configuration` so that should be picked up.

**Comment by mbogoevici** [comment] 2016-06-15 15:06
Let's do this: I'll try to provide a sample of using this from separate artifacts.

**Comment by solidgains** [comment] 2016-06-15 15:07
Right, so this is our SpringCloudStreamClient with @Service removed. 

```
@EnableBinding(MessageChannels.class)
public class SpringCloudStreamClient {
	
	private static final Logger LOGGER = LoggerFactory
			.getLogger(SpringCloudStreamClient.class);
	
	@Autowired MessageChannels msgChannel;
	
	public Object sendMessagetoKafka(ActivationDataInfo msg){
		LOGGER.info("Sending Message : " + msg);
		msgChannel.save().send(MessageBuilder.withPayload(msg).build());
		return new String("Success");
	}
}
```

**Comment by mbogoevici** [comment] 2016-06-15 15:10
And I suppose its package is one of the three listed in the `@ComponentScan` statement ?

**Comment by solidgains** [comment] 2016-06-15 15:12
To be thorough, here is our code:

```
Main class in child app: kafka handler .jar
@SpringBootApplication
public class ActivationQueueMessageServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(ActivationQueueMessageServiceApplication.class, args);
	}
	
}
```

```
@EnableBinding(MessageChannels.class)
public class SpringCloudStreamClient {
	
	private static final Logger LOGGER = LoggerFactory
			.getLogger(SpringCloudStreamClient.class);
	
	@Autowired MessageChannels msgChannel;
	
	public Object sendMessagetoKafka(ActivationDataInfo msg){
		LOGGER.info("Sending Message : " + msg);
		msgChannel.save().send(MessageBuilder.withPayload(msg).build());
		return new String("Success");
	}
}
```

```
public interface MessageChannels {

	@Output("activationMsgQueue")
	MessageChannel save();
}
```

**And in our Main, parent App:**

```
@Controller
@RequestMapping("/Activate")
public class POCSelectionController {
	
	@Autowired
	private SpringCloudStreamClient springCloudStreamClient;
	
	/** The Constant LOGGER. */
	private static final Logger LOGGER = LoggerFactory.getLogger(POCSelectionController.class);
	
	/**
	 * POC selection, get the view
	 */
	@RequestMapping(value = "/pocSelection", method = RequestMethod.GET) 
	public String pocSelection(ModelMap model) {
		model.addAttribute("pocSelectionForm", new POCSelection());
		return VelocityView.POC_VIEW;
	}
	
	/**
	 * POC selection, Post the form and redirect to view
	 */
	@RequestMapping(value = "/doPOCSelection", method = RequestMethod.POST) 
	public String doPOCSelection(@ModelAttribute("pocSelectionForm") POCSelection pocSelection, ModelMap model, HttpServletRequest httpServletRequest) {
		LOGGER.info(pocSelection.toString());
		ActivationDataInfo activationDataInfo = new ActivationDataInfo();
		activationDataInfo.setTn(Long.toString(pocSelection.getCustomerPOCSMS()));
		// TODO get accntNum from model activationDataInfo.setAcctNo((String) model.get("accountNumber"));
		activationDataInfo.setAcctNo("12345");
		activationDataInfo.setFlowType(".com");
		springCloudStreamClient.sendMessagetoKafka(activationDataInfo);
		return ActivationConstant.POC_SELECTION_DONE_REDIRECT;
	}
	
	/**
	 * POC selection completed view
	 */
	@RequestMapping(value = "/pocSelectionDone", method = RequestMethod.GET) 
	public String pocSelectionDone(ModelMap model, HttpServletRequest httpServletRequest) {
		return VelocityView.POC_DONE_VIEW;
	}
}
```

Our parent app main class:
```
@SpringBootApplication
@EnableAsync
@EnableCircuitBreaker
//@RefreshScope
//@Import(ActivatorWebRedisConfig.class)
//@Import(SpringCloudStreamClient.class)
@ComponentScan({"com.comcast.sparrow", "com.comcast.activation.rabittmq", "com.comcast.activation.message"})
public class ActivatorWebApplication extends WebMvcConfigurerAdapter {

	/**
	 * The main method.
	 *
	 * @param args the arguments
	 */
	public static void main(String[] args) {
		SpringApplication.run(ActivatorWebApplication.class, args);
	}
	
	/*
	@Bean(name = "MessageChannels")
	public MessageChannel messageChannel(){
		return new DirectChannel();
	}
	*/
	/**
	 * Locale resolver.
	 *
	 * @return the locale resolver
	 */
	@Bean
	public LocaleResolver localeResolver(){
		SessionLocaleResolver slr = new SessionLocaleResolver();
		slr.setDefaultLocale(Locale.US);
		return slr;
	}
	
	/**
	 * Locale change interceptor.
	 *
	 * @return the locale change interceptor
	 */
	@Bean
	public LocaleChangeInterceptor localeChangeInterceptor(){
		 LocaleChangeInterceptor lci = new LocaleChangeInterceptor();
	     lci.setParamName("sparrowLocale");
	     return lci;
	}

	/* (non-Javadoc)
	 * @see org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter#addInterceptors(org.springframework.web.servlet.config.annotation.InterceptorRegistry)
	 */
	@Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(localeChangeInterceptor());
    }
	
	/**
	 * Message source.
	 *
	 * @return the reloadable resource bundle message source
	 */
	@Bean
    public ReloadableResourceBundleMessageSource messageSource() {
            ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
            messageSource.setBasename("classpath:messages");
            return messageSource;
    }
	

	/**
	 * Servlet registration bean.
	 *
	 * @return the servlet registration bean
	 */
	@Bean
	public ServletRegistrationBean servletRegistrationBean(){
	    return new ServletRegistrationBean(new NuProxyServlet(),"/Activate/RENuProxy/*");
	}
	
}
```

**Comment by solidgains** [comment] 2016-06-15 15:13
@ComponentScan({"com.comcast.sparrow", "com.comcast.activation.rabittmq", **"com.comcast.activation.message"**})

It's that one.

**Comment by solidgains** [comment] 2016-06-15 15:16
> Let's do this: I'll try to provide a sample of using this from separate artifacts.

That would be awesome, thanks!

**Comment by mbogoevici** [comment] 2016-06-15 16:36
@solidgains 

Here is an example that works for me: https://github.com/mbogoevici/spring-cloud-stream-samples/tree/multi-modules/multiple-modules

It's pretty much to do what you are trying to do, so not sure where the differences are coming from, but maybe it's a starter. Let me know how that works. 

I still think it would better to create a separate configuration using `@EnableBinding` and have that imported into your application, but regardless, of that, this should work equally well.

**Comment by solidgains** [comment] 2016-06-15 18:51
Thanks for this. Things are still not getting wired up. Still trying a few things.

**Comment by mbogoevici** [comment] 2016-06-15 19:08
No problem. Let me know if you are able to reproduce based on my examples.

 If you can add the `package` and `import` statements to the examples you provided, I think that would be helpful as well.

**Comment by mbogoevici** [comment] 2016-06-16 04:02
Actually, can you confirm that `spring-cloud-stream` and the Kafka binder are added as dependencies in the second application, or included transitively via dependency on the initial jar ?

Otherwise, the `@EnableBinding` annotation would be indeed ignored, since its definition is not found on the classpath and then you wouldn't get the behaviour triggered by it - i.e. generation of `MessageChannels` bean. Pretty consistent with what you're seeing.

**Comment by solidgains** [comment] 2016-06-16 15:02
Sorry about the delay, some more information below. Our main app has a lot of dependencies, including spring integration, amqp and few other related modules. I have tried including the cloud-stream-kafka in the grale of the main app, but not the binder. Will try that. In terms of the imports, I checked, and they all line up with the sample you posted, meaning that I am using the same imports as in your sample, for MessageChannel, EnableBinding and all related cloud-stream objects.

```
dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-stream-kafka:1.0.2.RELEASE')
    compile("org.springframework.boot:spring-boot-starter-actuator")
   	compile("org.springframework.boot:spring-boot-starter-aop")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-websocket")
    compile("org.springframework.boot:spring-boot-starter-velocity")
    compile("org.springframework.boot:spring-boot-starter-integration:1.3.5.RELEASE")
    // explicitly use version 2.14.0 to address an issue in 2.12.5
    compile("org.mongodb:mongo-java-driver:2.14.0")
    compile("org.springframework.boot:spring-boot-starter-data-mongodb") {
        exclude group: 'org.mongodb', module: 'mongo-java-driver'
    }
    compile("org.springframework.data:spring-data-mongodb") {
        exclude group: 'org.mongodb', module: 'mongo-java-driver'
    }
      compile("org.springframework.cloud:spring-cloud-starter-feign")
    compile("org.springframework.cloud:spring-cloud-starter-parent")
    compile("org.springframework.cloud:spring-cloud-starter-eureka-server")
    compile("org.springframework.cloud:spring-cloud-starter-hystrix")
    compile('org.springframework.cloud:spring-cloud-starter-bus-amqp')
    compile('org.springframework.cloud:spring-cloud-starter-config')
    compile("org.springframework.cloud:spring-cloud-config-client")
    compile("org.springframework.cloud:spring-cloud-netflix-hystrix-amqp")
    compile('org.springframework.retry:spring-retry:1.1.2.RELEASE')
    compile("net.saliman:gradle-cobertura-plugin:2.2.4")
    compile('org.apache.commons:commons-lang3:3.0')
     compile('com.fasterxml.jackson.core:jackson-annotations:2.5.4')
    compile('nucaptcha:nucaptcha:1.0')
    //compile("com.comcast.activation.sparrow:account-validation:0.0.1-SNAPSHOT")
   
    compile("com.netflix.feign:feign-jackson:8.1.1")
    compile('com.netflix.feign:feign-gson:8.1.1')
    compile("com.x.activation.sparrow:common-util:0.0.26-SNAPSHOT")
    //compile("org.springframework.boot:spring-boot-starter-actuator")
    testCompile("org.springframework.boot:spring-boot-starter-test")
    compile("org.mockito:mockito-all:1.10.19")
    compile("appUtil:appUtil:2.1")
    compile("org.powermock:powermock-api-mockito:1.4.11")
    compile("org.powermock:powermock-module-junit4:1.4.11")
    //comcast-logging start
    compile("com.x.logging:comcast-logging:15.06.02")
    compile("log4j:log4j:1.2.17")
    //comcast-logging end
	
	compile('org.springframework.data:spring-data-redis:1.7.1.RELEASE')
    compile('org.springframework.session:spring-session-data-redis:1.1.1.RELEASE')
    //compile('com.github.kstyrc:embedded-redis:0.6')
	compile('com.x.activation:reporting-db-handler:0.0.8-SNAPSHOT')
    //slf4j - need version 1.7.21
    compile('org.slf4j:slf4j-api:1.7.21')
    compile('org.slf4j:jcl-over-slf4j:1.7.21')
    compile('org.slf4j:jul-to-slf4j:1.7.21')
    compile('ch.qos.logback:logback-classic:1.1.7') 
	
    testCompile("junit:junit"){
    	exclude group: 'org.hamcrest', module:'hamcrest-core'
    }    
    testCompile("org.codehaus.jackson:jackson-core-asl:1.1.0")
    testCompile("org.hamcrest:hamcrest-all:1.3")
    testCompile("com.jayway.jsonpath:json-path:0.9.1")
    testCompile("com.jayway.jsonpath:json-path-assert:0.9.1")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}
```

**Comment by solidgains** [comment] 2016-06-16 15:07
This is the only dependency in the kafka handler, 
compile('org.springframework.cloud:spring-cloud-starter-stream-kafka')

**Comment by mbogoevici** [comment] 2016-06-16 15:20
Thanks for sharing.

`compile('org.springframework.cloud:spring-cloud-starter-stream-kafka')` should be fine, as it pulls both the binder and the core.

Can you run the main app with the `-debug` flag and send me the output by any chance ?

**Comment by solidgains** [comment] 2016-06-16 15:27
Sure. Also, a piece of the previous logs I left out, it mentions something about spring integration

```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
[32m :: Spring Boot :: [39m      [2m (v1.2.7.RELEASE)[0;39m

Thu Jun 16 09:23:07 MDT 2016 INFO [APP:null TRACKING_ID:null ACCOUNT_NUM:null SESSION_ID:null] org.springframework.cloud.bootstrap.config.PropertySour
ceBootstrapConfiguration.initialize - Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name
='https://github.comcast.com/sparrow/config-test.git/activator-web/activator-web-qaauto.properties'], MapPropertySource [name='https://github.comcast.
com/sparrow/config-test.git/application.properties']]]
Thu Jun 16 09:23:07 MDT 2016 INFO [APP:null TRACKING_ID:null ACCOUNT_NUM:null SESSION_ID:null] org.springframework.context.support.AbstractApplication
Context.prepareRefresh - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5ae95707: startup date [Th
u Jun 16 09:23:07 MDT 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4c398c80
Thu Jun 16 09:23:09 MDT 2016 INFO [APP:null TRACKING_ID:null ACCOUNT_NUM:null SESSION_ID:null] org.springframework.core.io.support.PropertiesLoaderSup
port.loadProperties - Loading properties file from URL [jar:file:/C:/Users/bwarno001c/.gradle/caches/modules-2/files-2.1/org.springframework.integrati
on/spring-integration-core/4.1.6.RELEASE/7b95eb7f4c08070c345a723720fd5dbccf71b140/spring-integration-core-4.1.6.RELEASE.jar!/META-INF/spring.integrati
on.default.properties]
**Thu Jun 16 09:23:09 MDT 2016 INFO [APP:null TRACKING_ID:null ACCOUNT_NUM:null SESSION_ID:null] org.springframework.integration.config.IntegrationRegis
trar.registerHeaderChannelRegistry - No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderC
hannelRegistry will be created.**
Thu Jun 16 09:23:09 MDT 2016 INFO [APP:null TRACKING_ID:null ACCOUNT_NUM:null SESSION_ID:null] org.springframework.boot.logging.ClasspathLoggingApplic
ationListener.onApplicationEvent - Application failed to start with classpath: [file:/C:/Users/bwarno001c/Desktop/activation%20workspace/activator-web
-bob/bin/, file:/C:/Users/bwarno001c/.gradle/caches/modules-2/files-2.1/messageQueueHandler/messageQueueHandler/0.0.1-20160613.211854-1/bf170f3464f973
124dab03bd127c5e1a53df4019/messageQueueHandler-0.0.1-20160613.211854-1.jar, file:/C:/Users/bwarno001c/.gradle/caches/modules-2/files-2.1/org.springfra
mework.cloud/spring-cloud-starter-stream-kafka/1.0.0.RELEASE/c17a792e1080aad2d753a47e8021f665faa37765/spring-cloud-starter-stream-kafka-1.0.0.RELEASE.
jar, file:/C:/Users/bwarno001c/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-actuator/1.2.7.RELEASE/2f3ab8809a7d525f
f060fbe6cbbff546386cd122/spring-boot-starter-actuator-1.2.7.RELEASE.jar, file:/C:/Users/bwarno001c/.gradle/caches/modules-2/files-2.1/org.springframew

```

**Comment by mbogoevici** [comment] 2016-06-16 15:29
Also, this is using Spring Boot 1.2.7 - we require Spring Boot 1.3.5 for Spring Cloud Stream.

**Comment by solidgains** [comment] 2016-06-16 15:46
I upgraded it to 1.3.5. Getting a NoClassDefFound error 

![image](https://cloud.githubusercontent.com/assets/3255084/16123136/2b1d7246-33a7-11e6-86f6-5db4a74e6fdd.png)

I ran in debug mode in STS, console output is the same

**Comment by solidgains** [comment] 2016-06-16 15:58
Anyway, I think this may be leaving the realm of stream-kafka for now. I will try to figure this one out. I just wanted to say thanks again for the help, and if it does turn back around to be stream-kafka related I will post what I get.

**Comment by mbogoevici** [comment] 2016-08-23 01:21
Closing this for now, please reopen if issue resurfaces.

**Closed by mbogoevici** 2016-08-23 01:21 UTC
