### ISSUE TITLE
JSON deserializer conflict with Spring Boot Starter Web

### ISSUE THREAD

**Issue by alparius** [spring-cloud/spring-cloud-stream#2111] opened 2021-02-09 20:25 UTC
Hello!

I was instructed on StackOverflow, that I should share my issue here.

In short, when using both the `spring-cloud-stream` and `spring-boot-starter-web` libraries, the Consumer from the latter fails to deserialize the incoming JSON messages.

 [Link to the relevant question](https://stackoverflow.com/questions/66126051/json-deserializer-conflict-with-spring-boot-starter-web-and-spring-cloud-stream) with more details.

**Comment by olegz** [comment] 2021-02-10 07:12
So, I just generated brand new project and I can not reproduce the issue.
Here is the application code
```
@SpringBootApplication
public class DemoFunctionApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoFunctionApplication.class, args);
	}

	@Bean
	public Consumer<Person> consume() {
		return v -> System.out.println("RECEIVED: " + v);
	}

	public static class Person {
		private String name;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		@Override
		public String toString() {
			return "PERSON: " + name;
		}
	}
}
```
and here is the POM (to get the list of dependencies)
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>oz.function</groupId>
	<artifactId>demo-function</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo-function</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2020.0.1</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-rabbit</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

I am using Rabbit binder (for my own convenience), but that should not make any difference, since type conversion is not even done by s-c-stream, rather s-c-function, so binder has no affect on it. 

Aside from testing it with the current master branch, I also tested it with Hoxton.SR9 and Hoxton.SR8 and so far I receive fully converted `Person` object.

If you still believe there is an issue, please provide a way to reproduce it. Perhaps small project you can push to GitHub with the bare minimum that reproduces the issue

**Comment by alparius** [comment] 2021-02-16 22:32
Sorry for getting back to you this late.
We managed to solve the problem by doing exactly what you have done here, trying to reproduce my problem.

That is, upgrading the _springboot_ version to **2.4.2** from **2.3.5.RELEASE**, and _spring-cloud_ version to **2020.0.1** from **Hoxton.SR9**. 

I see you also tried going back to **Hoxton.SR9**, but maybe the problem is caused by a combination of both of these versions?

**Comment by olegz** [comment] 2021-02-22 13:24
Based on your response I am assuming there is no issue to address. Feel free to reopen if closed in error and provide more info

**Closed by olegz** 2021-02-22 13:24 UTC
Labels: waiting-on-feedback
