### ISSUE TITLE
StreamListener should only subscribe once to output flux

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1315] opened 2018-03-20 16:28 UTC
With a listener like this:

```java
	@StreamListener
	public Mono<Void> handle(@Input(Processor.INPUT) Flux<Message<?>> input,
			@Output(Processor.OUTPUT) FluxSender output) {
		return output.send(...);
	}
```

we get 2 subscriptions, one from the `DefaultFluxSender` and one from `PublisherToMessageChannelResultAdapter`. Maybe I just need to write the function in a different way but it looks like it might be a bug.

Cc @smaldini.

**Comment by sobychacko** [comment] 2018-03-20 22:31
@dsyer if we are binding a `FluxSender` explicitly on the output, then I was under the impression that the application programmatically calls `send(..)` on the output. Why are we returning `Mono<Void>` in that case? Is there a use case for that? But clearly, it seems to be a bug that it is subscribed twice when the method returns something while using `FluxSender`.

**Comment by sobychacko** [comment] 2018-03-20 23:36
@dsyer @olegz The subscription in the `DefaultFluxSender` is on the `Flux` that's coming in through the `send` method. It is adapted through the consumer here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/MessageChannelToFluxSenderParameterAdapter.java#L44
So anything that comes through that `Flux` is getting sent to the binding target (in this case the output channel). 
I ran a test and found out that the other subscriber in `PublisherToMessageChannelResultAdapter` is benign and the binding target is not called with the `send` here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-reactive/src/main/java/org/springframework/cloud/stream/reactive/PublisherToMessageChannelResultAdapter.java#L58
I think that is presumably because we are sending a `Mono<Void>` from the method and nothing comes through although it is subscribed. 
I believe that the above method can be written like this and that second subscription could be avoided. 
```
@StreamListener
	public void handle(@Input(Processor.INPUT) Flux<Message<?>> input,
			@Output(Processor.OUTPUT) FluxSender output) {
		return output.send(...);
	}
```

**Comment by olegz** [comment] 2018-03-21 13:03
@sobychacko I believe you're correct. Just did some more digging and experimenting on Spring Cloud Function side (which is what I believe Dave was referring to) and changing signature to void seems to confirm your findings.
As a side note, this is yet another reason why we are already discussing a different approach for declarative handlers. The above method is NOT a `@StreamListener`. It's a declaration of the entire `MessageHandler` which as you know _only_ defines `void` return type. So at best it's a `@MessageHandler` or `@MessageDelegatingConsumer` or something like that, but not `@StreamListener`.

**Comment by smaldini** [comment] 2018-03-21 20:07
I think something is still off tho, FluxSender signature has 2 "issues" IMO:
- It accepts a Flux (it should be `Publisher`)
- It returns a Mono<Void> so as all reactive API and unlike stuff like CompletableFuture we only start doing things on the returned mono.subscribe(). In WebFlux that's what we do and that allows us to compose in a single final flow per request. 

Here if you call send more than once it will resubscribe a new flow more than once, but also it does it as you call send preventing any further composition to happen which is the SCF case.

In reactive world i should be able to do : 

```java
@StreamListener
	public void handle(@Input(Processor.INPUT) Flux<Message<?>> input,
			@Output(Processor.OUTPUT) FluxSender output) {
	    output.send(headers)
                    .then(output.send(input))
                    .then(output.send(trailer))
                    .subscribe();
	}
```

**Comment by dsyer** [comment] 2018-03-21 21:43
I don't want to subscribe though. I want the framework to do that for me. So `Mono<Void>` is a better return value for such a listener.

Maybe you are right @olegz from a purist perspective (that my method is not a pure listener), but I think you are wrong that `void` is the right return type. It's a smell, in a reactive API. Note also that your code does not compile (you return something from a `void ` method). I need to be able to return a `Publisher` that the framework will subscribe to (once), to pull through the data from upstream and maintain the balance of the universe.

**Comment by olegz** [comment] 2018-03-21 21:59
@dsyer just to clarify, this is something Soby and I have been discussing for a while now - the fact that `@StreamListener`'s currently supports both _imperative_ and _declarative_ style of programming handlers. . . well `handlers` or `handler methods`  to be precise (which are orthogonal IMHO). It also affects `StreamListenerAnnotationBeanPostProcessor` which is becoming quite complex. But that is for the future.

As for the `void` vs. `Mono`, I am definitely not an expert and quite possibly approached it from a different angle.
The method above does compile and runs once `return` is removed. That is what was referring to earlier today as I played with it in SCF.
As for the rest I think  am getting your point, but need to better understand Flux and possibly ask @smaldini  for some help unless @sobychacko gets there first ;)

**Comment by sobychacko** [comment] 2018-03-22 20:35
@dsyer @olegz the code below should do the same thing that you are trying through `FluxSender` on the output. Any particular reason why you need to use a `FluxSender`? We will still need to address the problems with FluxSender addressed on this issue. 

```java
@StreamListener
@SendTo(Processor.OUTPUT)
public Flux<Message<?>> handle(@Input(Processor.INPUT) Flux<Message<?>> input) {
     return input.groupBy(this::select).flatMap(group -> group.key().process(group));
}
```

**Comment by smaldini** [comment] 2018-03-23 17:29
@sobychacko @olegz so the issue is specific to FluxSender for me which is maybe then better to address specifically in #1316 ?
The two points: 
- FluxSender should accept any Publisher not only Flux
- FluxSender should not subscribe on method call but when the returned Mono<Void> is subscribed

**Comment by sobychacko** [comment] 2018-03-23 17:59
@smaldini If @dsyer is ok with the approach, then we can specifically address the issues with `FluxSender` as part of #1316.

**Comment by dsyer** [comment] 2018-03-23 18:37
I already refactored to remove the `FluxSender` and return a `Flux<Message<?>>` (as Soby suggested). So you can do whatever you fee like as long as that still works, for my sake anyway.

**Comment by sobychacko** [comment] 2018-03-23 18:45
Thanks, @dsyer. Closing this issue and we will address the `FluxSender` issues as part of #1316.

**Closed by sobychacko** 2018-03-23 18:45 UTC
