### ISSUE TITLE
There is a lazy loading bug in this place，afterSingletonsInstantiated

### ISSUE THREAD

**Issue by dingdaoyi** [spring-cloud/spring-cloud-stream#2580] opened 2022-12-07 06:43 UTC
https://github.com/spring-cloud/spring-cloud-stream/blob/3c7c5230c68431d68b9b26eef3bdfe7d08d735db/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L214

When the send method is earlier than afterSingletonsInstantiated, the following problems will occur
			FunctionInvocationWrapper functionToInvoke = this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, outputContentType.toString());
			this.streamBridgeFunctionCache.put(outputContentType, functionToInvoke);

functionToInvoke  is null ，Causes subsequent null pointers

**Comment by olegz** [comment] 2023-01-05 14:37
The only way I see this happening if there is some type of synchronization issue as the first thing we're doing in `send()` method is verifying that bridge is initialized https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L150

**Comment by olegz** [comment] 2023-01-13 07:27
I am going to close it due to the lack of follow up from the reporter. 
Feel free to reopen it or raise a new one providing requested details and way to reproduce it. 
Also keep in mind that if you are trying to send something before `afterSingletonsInstantiated` was executed there is a very good chance that other application context initialisation processes have not fully finished, resulting on some other issue. So the real question what is it that you are doing that forces you to send 'early'

**Closed by olegz** 2023-01-13 07:27 UTC
Labels: waiting-on-feedback
