### ISSUE TITLE
Support strongly-typed interface definitions

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-stream#944] opened 2017-05-03 22:28 UTC
I have a channel `foo-events` that handles messages whose payload is type `Foo`. Right now, I can use SCS to bind like this:

```
public interface FooSource {
    @Output("foo-events")
    MessageChannel output();
}

...
fooSource.output().send(MessageBuilder.withPayload(myFoo).build());
```

While this is a great help, it would be even better if, in line with Spring Integration and the `@StreamListener`, I could define the interface like this:

```
public interface FooSource {
    @Output("foo-events")
    void sendFoo(@Payload Foo foo);
}
```

and have the methods automatically create `GenericMessage` instances.

**Comment by artembilan** [comment] 2017-05-03 22:32
You can do that already right now with the existing Spring Integration [Messaging Gateway support](http://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#gateway):
````java
@MessagingGateway(defaultRequestChannel = "foo-events")
public interface FooSource {

    void sendFoo(Foo foo);

}
````
But yeah, you have to declared both species: Binding and that `@MessagingGateway`...

**Comment by chrylis** [comment] 2017-05-03 22:34
Right, that's what I meant with my comment, but right now I have to choose between `@MessagingGateway` and `@EnableBinding`. I want both! ;-)

**Comment by artembilan** [comment] 2017-05-03 22:39
??? You have to declare both right now, just because ` @MessagingGateway` doesn't do binding.
But it provides what you need: strong-typed send hook. In addition to the `@EnableBinding`. You can't choose as you said.

What am I missing in your comments?

**Comment by chrylis** [comment] 2017-05-04 02:13
I don't understand your response. I'm saying that if I use `@EnableBinding`, I get automatic binding to the MQ but I have to wrap the `Message` myself. If I use `@MessagingGateway`, I get automatic type conversion but I have to declare the channel binding explicitly.

**Comment by artembilan** [comment] 2017-05-04 02:31
What I mean that you have to declare `@EnableBinding` and leave that interface with the `@Output` annotation to bind the channel to MQ. The `@MessagingGateway` will use that channel to send to MQ. You should just declare such a gateway in addition to existing Outbound binding and use its interface instead of message channel.

What do you mean that you have to declare binding manually? As for me everything remains transparent for target sender.

**Comment by chrylis** [comment] 2017-05-08 15:34
Okay, so you mean to set up two separate interfaces, one for use with `@EnableBinding` and one with `@MessagingGateway`? That seems doable, for now--but it would also be nice to be able to combine them so that `@EnableBinding` could be used directly on an `@MessagingGateway`.

**Comment by artembilan** [comment] 2017-05-08 15:56
Glad to see that we are in consensus finally!

Re. combine...
Well, even if that is possible with some code magic, I don't think that we should mix concerns.
`@EnableBinding` with its `@Input/@Output` is for building infrastructure upfront target application logic.
The `@MessagingGateway`, on the other hand, is very close to the application logic and is just a user of the `@EnableBinding` bits.

It's much cleaner to separate those responsiblities and don't confuse yourself with unexpected behavior.

But yeah... That is just IMHO.
I don't mind to hear any other opinion.

/CC @garyrussell , @mbogoevici

**Comment by chrylis** [comment] 2017-05-10 03:40
Since the idea behind SCS is to make the common use cases simple, requiring duplicate interfaces just to get what's from a client perspective essentially a conversion service will get clumsy in a hurry. It feels _just a little bit_ like EJB2... I understand the general preference not to mix concerns, but these seem very closely related. I am interested in other perspectives.

**Comment by chrylis** [comment] 2017-05-15 02:10
As a followup, the binding magic apparently does not work on the receiving end.

I have declared a `Sink` interface with an `@Input` channel that theoretically should be managed entirely by SCS. I have explicitly declared `stream.cloud.stream.default.content-type: application/json`. I expected SCS to therefore deserialize the JSON objects before inserting them into the `@Input` channel. However, when I tried to use `@ServiceActivator` (because of its more general API), I got an exception saying that SpEL was trying to call the method with a `String` (presumably the JSON body).

I understand the difficulty in deserializing at message injection if type info is not provided in the JSON, but this does seem to step on the separation-of-concerns design goal.

**Comment by artembilan** [comment] 2017-05-15 02:23
Try `@StreamListener` instead of `@ServiceActivator`. It supports Content-Type negotiation only since Spring Integration 5.0: http://docs.spring.io/spring-integration/docs/5.0.0.M3/reference/html/whats-new.html#_content_type_conversion.

On the other hand, please, don't mix concerns again. That is not channel responsibility to deserialize data. It's work only delive the data from the endpoint to the handler. That's already the handler task to deal with data on its own.

Not sure how this relates to the original gateway discussion though...

**Comment by chrylis** [comment] 2017-05-17 10:38
It's a little unclear to someone new to SCS what responsibilities exactly a "binding" entails. Since I set a content type on the binding, and the binding creates an injectable SI channel and wires it into a message queue, I thought that the handling of the content type would sit between the MQ subscription and the SI channel object.

(The reason for preferring `@ServiceActivator` if it were practical is that `@StreamListener` has a number of limitations that the former doesn't, particularly including that multiple listeners can't return messages of their own.)

**Comment by artembilan** [comment] 2017-05-17 14:27
>  between the MQ subscription and the SI channel object.

That isn't possible because there is no target expected value type knowledge yet.
Your `@ServiceActivator` or `@StreamListener` is on some custom service method. So, there is a parameter from which we can infer the type. In case of `@ServiceActivator` there is a `ConversionService` to convert incoming `payload` to the expected method parameter type. Not so useful in case of stream application: mostly the data is just `byte[]`. When we use `@StreamListener`, the `content-type` header is consulted to convert that `byte[]` to the expected parameter type: http://docs.spring.io/spring-cloud-stream/docs/Chelsea.SR2/reference/htmlsingle/index.html#_using_streamlistener_for_automatic_content_type_handling.

You are mixing concerns again: it's fully not `MessageChannel` responsibility to deal with `payload` in transferred messages. Consider the `MessageChannel` abstraction in Spring Integration (Spring Cloud Stream) as a destination on Message Brokers: queues/topic in JMS/MQ, queues in AMQP, partition in Kafka etc. They do nothing with the data: only used for persistence store and loosely coupling principle achievement.

The binding in Spring Cloud Stream is just a bridge between target message broker and your stream application. In this case it is pretty easy for you to replace binder without breaking logic in the target application. Just because everything inside is based on the Spring Integration abstractions: endpoint ->message channel -> message handler. And that's why I'm saying you through this topic that the goal is to distribute responsibility to the proper components and don't mix abstraction such a gateway for binding.

Right, there is a bit more codding with Spring Integration and Spring Cloud Stream, than with the raw Java, when you don't care loosely coupling principle. But at the same time it is much easier to modify a part of your application without affecting others. Maybe you should rethink your application design and don't apply messaging everywhere, if you are starting to imaging EJB2...

**Comment by mbogoevici** [comment] 2017-07-11 20:12
Closing for now as `MessagingGateway` + binding provides good enough coverage.

**Closed by mbogoevici** 2017-07-11 20:12 UTC
Labels: wontfix
