### ISSUE TITLE
Error channel naming enhancement

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-stream#2469] opened 2022-08-04 17:38 UTC
Please add support for something like a binding name alias so that different destinations can be used but they can always be set to the same error channel bean name.

This enhancement request is being requested after the suggestion posted in [this issue](https://github.com/spring-projects/spring-integration/issues/3870). There it was suggested that the enhancement requested originally opened against Spring Integration would be better suited with Spring Cloud Stream.

**Comment by artembilan** [comment] 2022-08-04 18:25
I think the problem is in the `AbstractMessageChannelBinder` where we register an error channel bean:
```
	String errorChannelName = errorsBaseName(destination, group, consumerProperties);
...
	protected String errorsBaseName(ConsumerDestination destination, String group,
			C consumerProperties) {
		return destination.getName() + "." + group + ".errors";
	}
```
So, the name of the bean is really based on a destination.
However I feel like it has to be based on the binding name since already this one is closer to the application logic rather than environment this application is deployed in.
In that `registerErrorInfrastructure()` method we an access to this `consumerProperties.getBindingName()`.
From here I wonder why the choice was really about a destination name, but not the binding we do in the application...

**Comment by olegz** [comment] 2022-08-31 14:19
I believe this issue has been addressed with the upcoming functional error handling. It's already available in SNAPSHOTS for both 4.x and 3.2.x. Also, 3.2.5 is coming out very shortly (few days), so it will be available to you
Here is the link to the updated ref doc with more details - https://docs.spring.io/spring-cloud-stream/docs/3.2.5-SNAPSHOT/reference/html/spring-cloud-stream.html#_handle_error_messages

Please let us know if that is what you are looking for

**Comment by olegz** [comment] 2022-09-07 10:20
I am going to close it as I believe the issue has been addressed with functional error handling approach discussed earlier.
Feel free to reopen or raise a new one if the issue persists.

**Closed by olegz** 2022-09-07 10:20 UTC
