### ISSUE TITLE
Spring Cloud Stream combined with Jasypt starter decrypts properties that are overridden

### ISSUE THREAD

**Issue by michael-barker** [spring-cloud/spring-cloud-stream#973] opened 2017-05-21 16:13 UTC
This issue didn't exist in Camden SR6.  When upgrading to Camden SR7 or Dalston Release then encrypted properties that are overridden by an active profile are still being decrypted.  Normally the active profile would have a different Jasypt encryptor key which causes an exception when the overridden value is decrypted with the wrong key.

The Jasypt starter works with Camden SR7 and Dalston Release, it's only when using Spring Cloud Stream that this is reproducible.  The only update I saw in SR7 was a fix for #810, not sure if that's what caused this issue.

I created a small example app to reproduce this issue.
[https://github.com/michael-barker/jasypt-spring-cloud-stream-bug](https://github.com/michael-barker/jasypt-spring-cloud-stream-bug)

Jasypt Spring Boot Starter
[https://github.com/ulisesbocchio/jasypt-spring-boot](https://github.com/ulisesbocchio/jasypt-spring-boot)

I don't know if this should be considered an issue with Spring Cloud Stream or Jasypt.  If this is an issue with Jasypt then please close and I'll open an issue over there.

**Comment by mbogoevici** [comment] 2017-05-22 17:22
@michael-barker Spring Cloud Stream doesn't interact directly with jasypt, but at a quick glance over the examples, I noticed that the examples use Spring Boot 1.5.3 (which was released after Camden SR6, but upon which both the other releases are based). Is it possible to reproduce this with Boot 1.5.3 but without Spring Cloud Stream ?

**Comment by michael-barker** [comment] 2017-05-22 20:58
@mbogoevici The issue is only reproducible when using Spring Cloud Stream with Spring Boot 1.4.5 / Camden SR7 and Spring Boot 1.5.3 / Dalston Release.  I cannot reproduce the issue when using Spring Cloud Stream with Spring Boot 1.4.5 / Camden SR6.  I also cannot reproduce in any Spring Boot / Cloud combination if I don't have a dependency on Spring Cloud Stream.

While Spring Cloud Stream doesn't have anything to do with Jasypt, it seemed like Spring Cloud Stream was causing an issue with Jasypt decrypting properties due to properties being loaded that should be overridden by an active profile.

**Comment by mbogoevici** [comment] 2017-05-22 21:49
@michael-barker Thanks for confirming. Yes, I can reproduce it locally. I'll need some time to dig into it.

**Comment by mbogoevici** [comment] 2017-05-23 00:38
It's a bit early to have a full diagnosis, but this seems to happen as a result of some changes in Spring Boot that have taken place between Spring Boot 1.5.1 and Spring Boot 1.5.2. A simplified version that reproduces the issue without SCSt can be found here: https://github.com/mbg-scratchpad/scst-gh-973 - the correlation is that in the case of SCSt, the binder is created in a child context, so that's what triggers the issue. Will continue looking into this, but it is potentially a bad interaction between Boot and Jasypt. cc/@dsyer

**Comment by mbogoevici** [comment] 2017-05-23 18:53
@michael-barker 

There are two tests in this repository that reproduce issues with the Jasypt Boot integration and access to property sources. These issues are triggered by Spring Cloud Stream functionality (the creation of child contexts) in combination with the recent change in Spring Boot, but the underlying cause is basically that the Jasypt integration wraps all property sources into its own implementation. Since each profile creates a property source, some profiles will contain values that cannot be decrypted. That is not apparent when requesting an individual property from the environment, but can be reproduced while actually trying to iterate the property sources.  That can be easily reproduced below:

https://github.com/mbg-scratchpad/scst-gh-973/blob/master/src/main/java/com/example/jasypt/EnvironmentIteratingApplication.java

Also, here's a simple example creating a context whose environment is merged with the root context.

https://github.com/mbg-scratchpad/scst-gh-973/blob/master/src/main/java/com/example/jasypt/EnvironmentMergingApplication.java

Both are pretty reasonable use cases, even if not very common - so it seems that the underlying cause is the Jasypt implementation. One recommendation that @dsyer provided was something similar to what is currently done in Spring Cloud for property decription: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L108

**Comment by mbogoevici** [comment] 2017-07-11 20:48
Closing this as it is been inactive for a while. @michael-barker please follow up if needed.

**Closed by mbogoevici** 2017-07-11 20:48 UTC
