### ISSUE TITLE
AvroSchemaRegistryClientMessageConverter.extractSchemaReference throws NullPointerException

### ISSUE THREAD

**Issue by parunruaivo** [spring-cloud/spring-cloud-stream#694] opened 2016-10-25 11:54 UTC
The parameter `mimeType` is null

``` java
private SchemaReference extractSchemaReference(MimeType mimeType) {
    SchemaReference schemaReference = null;
    Matcher schemaMatcher = this.versionedSchema.matcher(mimeType.toString());
    if (schemaMatcher.find()) {
        String subject = schemaMatcher.group(1);
        Integer version = Integer.parseInt(schemaMatcher.group(2));
        schemaReference = new SchemaReference(subject, version, AVRO_FORMAT);
    }
    return schemaReference;
}
```

is passed from `convertToInternal` where `conversionHint` could be null

``` java
    @Override
    protected Object convertToInternal(Object payload, MessageHeaders headers, Object conversionHint) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            MimeType hintedContentType = null;
            if (conversionHint instanceof MimeType) {
                hintedContentType = (MimeType) conversionHint;
            }
            Schema schema = resolveSchemaForWriting(payload, headers, hintedContentType);
            DatumWriter<Object> writer = getDatumWriter((Class<Object>) payload.getClass(), schema);
            Encoder encoder = EncoderFactory.get().binaryEncoder(baos, null);
            writer.write(payload, encoder);
            encoder.flush();
        }
        catch (IOException e) {
            throw new MessageConversionException("Failed to write payload", e);
        }
        return baos.toByteArray();
    }
```

Checking if the `mimeType` is null before using it worked for me.

**Comment by mbogoevici** [comment] 2016-10-25 13:19
Thanks for reporting. Can you provide an example that reproduces the issue?

**Comment by parunruaivo** [comment] 2016-10-25 14:36
Sure, check this repo https://github.com/parunruaivo/stream-schema-test and run the test `customerCreatedEvent`

**Comment by mbogoevici** [comment] 2016-10-25 14:42
Thanks. 

I'll check this - but you can remove the bean definition at https://github.com/parunruaivo/stream-schema-test/blob/master/src/main/java/com/parunruaivo/infrastructure/SchemaConfig.java#L22 

That bean will be registered automatically via https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroMessageConverterAutoConfiguration.java

**Comment by parunruaivo** [comment] 2016-10-25 15:53
That was my workaround to make it work,  I added `@EnableSchemaRegistryClient` to `class Application` like the reference
```java
@SpringBootApplication
@EnableSchemaRegistryClient
public class Application {
```
but I had a exception that there wasn't a MessageConverter for a content-type application/*+avro,
I'm trying to reproduce the bug in the repo, later I will check in the other project where the exception was thrown.

**Comment by parunruaivo** [comment] 2016-10-25 16:06
I updated the repo without using SchemaConfig, but now getting `org.springframework.cloud.stream.converter.ConversionException: No message converter is registered for application/*+avro`

In the other project, the server is separate from the clients with the same result.

Thanks.

**Comment by mbogoevici** [comment] 2016-10-26 03:38
@parunruaivo thanks for the follow-up. One possible cause of this is that that Avro is an optional dependency of the project (since there may be other schemas supported in the future). We'll need to clarify this in the documentation.

Can you check if it is on the classpath, if please try adding:

```
<dependency>
			<groupId>org.apache.avro</groupId>
			<artifactId>avro</artifactId>
			<version>1.8.1</version>
		</dependency>
```

to your project.

**Comment by parunruaivo** [comment] 2016-10-26 11:40
Yes, It was already used because I was getting that some avro dependencies where missing.

I found something that may help, using 
```java
@SpringBootApplication(scanBasePackages = {"com.parunruaivo","org.springframework.cloud.stream.schema"})
```
the class `AvroMessageConverterAutoConfiguration` is not being instantiated but If I change it for 
```java
@SpringBootApplication(scanBasePackageClasses = {SchemaRegistryServerApplication.class, Application.class})
```
 at least now the converter is registered.

**Comment by parunruaivo** [comment] 2016-11-04 14:04
If `AvroMessageConverterAutoConfiguration ` is used then the NullPointerException dissapear, now I´m using the client without problems.

Maybe the previous comment is related to the entity scan issue wich made me use a custom bean and getting the Exception.

**Comment by mbogoevici** [comment] 2016-11-04 14:07
Thanks for following up @parunruaivo - can we close this for now?

**Comment by parunruaivo** [comment] 2016-11-04 14:08
Yes, and thanks.

**Comment by mbogoevici** [comment] 2016-11-04 14:11
Cool, thanks!

**Closed by mbogoevici** 2016-11-04 14:11 UTC
Labels: bug
