### ISSUE TITLE
Setting custom headers in @StreamListener method throws IllegalStateException

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-stream#1744] opened 2019-06-21 13:51 UTC
Setting custom headers on a message inside a `@StreamListener` method is throwing an exception. I have enabled debug logging but no further information is surfaced apart from the exception shown below. When I do _not_ set the custom headers the message is sent successfully. Is this supported?

```
private BinderAwareChannelResolver resolver;

@StreamListener(target = ChannelBindings.INPUT)
public void handleMessage(@Payload Foo foo, @Headers MessageHeaders headers) {
        // do stuff with "foo" object
        Message outboundMessage = MessageBuilder.withPayload(foo)
                .setHeader(MessageHeaders.CONTENT_TYPE, "application/x-custom-header")
                .setHeader("X-Custom-Header", "customValue")
                .build();
        resolver.resolveDestination(foo.getDestination()).send(outboundMessage);
    }
```

The following exception is thrown:

```
java.lang.IllegalStateException: Failed to convert message: 'GenericMessage [payload=Foo(super=SuperFoo(someField=bar)), headers={id=ad787854-d3ef-4e50-20e4-91b92eb96a1c, contentType=application/x-custom-header, X-Custom-Header=customValue, timestamp=1561124633190}]' to outbound message.
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor.doPreSend(MessageConverterConfigurer.java:389)
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:423)
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:608)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:443)
        ... 47 more
```

**Comment by garyrussell** [comment] 2019-06-21 13:57
I think the issue is the unknown content type; the converter doesn't know how to deal with it.

>`OutboundContentTypeConvertingInterceptor`

**Comment by boonware** [comment] 2019-06-21 15:09
Yep, that's rh problem. I used a custom content type to select my custom message converter. But I realized I can still use application/json and my converter will take precedence over any existing JSON converters.

**Comment by olegz** [comment] 2019-06-21 16:05
So, there is no issue, correct? If so please close it or we can close it as well

**Comment by boonware** [comment] 2019-06-22 00:32
Unless you think that handling custom content types should be supported then I'm OK to close. I'll leave that call up to you :)

**Comment by garyrussell** [comment] 2019-06-22 01:37
It's not clear what you mean.

If you are NOT using `nativeEncoding` (which is implied by the error), the framework needs to know how to convert a `Foo` to a `byte[]`. In order to do that, it needs a custom converter in the interceptor (which uses a `CompositeMessageConverter`). If there's not a mechanism to add your own converter(s) to the interceptor, there probably should be.

 If you ARE using `nativeEncoding` (e.g. with Kafka), then you need to configure the producer with a custom `Serializer` that knows how to convert a `Foo` into whatever `application/x-custom-header` means (in terms of a `byte{}`). Or, you can add your own channel interceptor to do the conversion.

**Comment by garyrussell** [comment] 2019-06-23 18:20
> If there's not a mechanism to add your own converter(s) to the interceptor, there probably should be.

See [Provided Message Converters](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.2.0.RELEASE/spring-cloud-stream.html#_provided_messageconverters), and the link to [User-defined Message Converters](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.2.0.RELEASE/spring-cloud-stream.html#spring-cloud-stream-overview-user-defined-message-converters). You need to add a converter that understands how to convert your foo to a `byte[]` with that contentType.

**Comment by sabbyanandan** [comment] 2019-07-02 14:32
A solution was provided, so closing it.

**Closed by sabbyanandan** 2019-07-02 14:32 UTC
Labels: waiting-on-feedback
