### ISSUE TITLE
Cannot Send Kafka Tombstone Messages

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-stream#2015] opened 2020-08-25 04:58 UTC
Currently we try to use kafka tombstone messages in our services. We created the following setup to play around with the  functionality
```
@SpringBootApplication
class TombstoneApplication {

    @Bean
    fun supplier(): Supplier<Flux<out Message<out Any?>>> = Supplier {
        Flux.range(0, 3)
                .delayElements(Duration.ofSeconds(1))
                .doOnNext { println("output $it") }
                .map {
                    MessageBuilder
                            .withPayload(KafkaNull.INSTANCE)
                            .setHeader(KafkaHeaders.MESSAGE_KEY, "42")
                            .build()
                }
    }

    @Bean
    fun consumer(): Function<Flux<Int>, Mono<Void>> = Function {
        it
                .doOnNext { println("Got stuff: $it") }
                .then()
    }
}
```
but end up with
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.messaging.converter.MessageConversionException: Could Not Convert Output
Caused by: org.springframework.messaging.converter.MessageConversionException: Could Not Convert Output
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertOutputValueIfNecessary(SimpleFunctionRegistry.java:682) ~[spring-cloud-function-context-3.0.9.RELEASE.jar:3.0.9.RELEASE]
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.lambda$convertOutputPublisherIfNecessary$6(SimpleFunctionRegistry.java:727) ~[spring-cloud-function-context-3.0.9.RELEASE.jar:3.0.9.RELEASE]
    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.signal(MonoDelayUntil.java:259) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.MonoDelayUntil$DelayUntilTrigger.onComplete(MonoDelayUntil.java:338) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:118) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```
According to @garyrussell he thought this bug was fixed and asked me to open a new issue here.
Do you have any suggestions what's going on here?

**Comment by olegz** [comment] 2020-08-25 13:05
What version you are using?

**Comment by kschlesselmann** [comment] 2020-08-25 13:25
@olegz Spring Boot 2.3.3 and Spring Cloud Hoxton.SR7

**Comment by olegz** [comment] 2020-08-25 13:26
I meant spring-cloud-stream version. It's not clear from the stack trace

**Comment by kschlesselmann** [comment] 2020-08-25 13:27
Everything is handled by the BOMs. But it's 3.0.7.RELEASE in this case.

**Comment by sobychacko** [comment] 2020-08-27 17:58
@kschlesselmann The problem is that the `KafkaNullConverter` bean defined [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L146) is only available as part of the binder context. Therefore, this converter is never seen during the conversion phase by the main context. @olegz is going to address this in the next SR release of Horsham. In the meantime, as a workaround, you can copy [this converter](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaNullConverter.java) in your project and then define a bean for that in your application. Redefining the bean without making a copy of your own `KafkaNullConverter` will not work as there is a `ConditionalOnMissingBean` in the binder configuration definition and thus still be made only part of the binder context. The following worked for me.
```
@Bean
public com.example.KafkaNullConverter kafkaNullConverter() {
   return new com.example.KafkaNullConverter();
}
```

**Comment by garyrussell** [comment] 2020-08-27 18:16
Confirmed; thanks Soby.

```java
@SpringBootApplication
public class Gitter79Application {

	public static void main(String[] args) {
		SpringApplication.run(Gitter79Application.class, args);
	}

	@Bean
	Supplier<Message<?>> supplier() {
		return () -> new GenericMessage<>(KafkaNull.INSTANCE,
				Collections.singletonMap(KafkaHeaders.MESSAGE_KEY, "foo".getBytes()));
	}

	@Bean
	KafkaNullConverter converter() {
		return new KafkaNullConverter();
	}

	@Bean
	Consumer<Message<?>> consumer() {
		return System.out::println;
	}

}
```
```properties
spring.cloud.stream.bindings.consumer-in-0.destination=supplier-out-0
spring.cloud.function.definition=supplier;consumer
```
>`GenericMessage [payload=org.springframework.kafka.support.KafkaNull@48c04e6c, headers={kafka_offset=5, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@f329567, deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, kafka_receivedMessageKey=[B@789a5543, contentType=application/json, kafka_receivedTopic=supplier-out-0, kafka_receivedTimestamp=1598552083599, kafka_groupId=anonymous.25054183-f9c1-4fb1-aecb-bdbb4e3817cd}]`

**Comment by kschlesselmann** [comment] 2020-08-31 05:25
@sobychacko @garyrussell The current Hoxton.SR8 release seems to work. I have to write the consumer like
```
    @Bean
    fun consumer(): Function<Flux<Message<Any>>, Mono<Void>> = Function {
        it
                .filter { it.payload !is KafkaNull }
                .map { it.payload }
                .doOnNext { println("Got stuff: $it") }
                .doOnError { println("Booom!!!! $it") }
                .then()
    }
```
though in order to keep away the null pointer exceptions. Is there a more elegant way to filter out the tombstones on the consumer side?

**Comment by kschlesselmann** [comment] 2020-08-31 12:35
Hm, looks like the casting doesn't work with complex objects. I think we're going to need a better approach :-(

**Comment by olegz** [comment] 2020-08-31 12:38
@kschlesselmann I think you may be referring to the limitation of Java's type system that we have hit as well,
Basically you have to kind of double cast:

```
Object payload = message.getPayload();
if (payload instanceof KafkaNull) {
    . . .
}
```

**Comment by kschlesselmann** [comment] 2020-09-03 07:00
@olegz Could you elaborate our example a little bit more? I'm not sure I can follow you.

**Comment by sabbyanandan** [comment] 2020-09-15 15:00
@kschlesselmann: This appears to have been fixed in https://github.com/spring-cloud/spring-cloud-stream/commit/7d76a109a84c0a9a7f75e9d2480f3e9f2aeca066 and https://github.com/spring-cloud/spring-cloud-stream/commit/2acfd34e43027ef43a0b58d1d5035c577d12eec7 — both of them are wrapped in `3.0.8.RELEASE`.

Please try upgrading and let us know if you see any anomaly.

**Comment by sabbyanandan** [comment] 2020-09-15 15:01
Otherwise, Hoxton.SR8 will automatically bring the fix in SCSt, too.

**Closed by sabbyanandan** 2020-09-15 15:00 UTC
